src/events/events.service.spec.ts
src/events/events.service.ts
src/users/users.service.spec.ts
src/users/users.service.ts

In our 3 ranking queries, we don't ignore events with 0 points when
trying to get the latest occuring event to rank users who earned
their points sooner.
Wrote tests
```
[ ] Yes
```

Ignore 0 point events in ranking last_occured_at

---

src/common/constants.ts
src/events/events.service.spec.ts

We mentioned in Discord that we were going to update the PR points limit to 5k, so this bumps up the weekly limit.
Points limit should show differently on user pages on the testnet website.
```
[ ] Yes
```
This should not be breaking.

Update the PR points limit to 5000

---

src/users/interfaces/serialized-user.ts
src/users/users.service.ts
src/users/utils/user-translator.ts

This field doesn't have any use on the frontend as far as I can tell, so may as well remove it to save some bandwidth.
Tests should pass, login should still be possible.
```
[ ] Yes
```
Not as far as I can tell. It has potential to break things, but I couldn't find usages of it in website-testnet.

Remove last_login_at field from SerializedUser

---

bin/check_for_dotenv.sh
package.json

Makes setup a little easier for this repository by creating a default `.env` if one doesn't already exist. 
Tested manually
```sh
~/git/ironfish-api  feature/iro-1503 ✔                                                                                                                                                                            
▶ yarn start
yarn run v1.22.17
$ bash bin/check_for_dotenv.sh
'.env' does not exist. Creating one using '.env.template'
$ node build/main.js
Starting master process PID 94879
```
```
[ ] Yes
```

chore(api): Add script to default .env if not present

---

prisma/migrations/20220121212448_sync_db_state/migration.sql
prisma/schema.prisma

Create a migration to sync the FK names from the events table, which is
just drift from Prisma version upgrades.
Add `map` argument to `@@unique` to keep the unique constraint name in
the database as expected. This is needed due to naming constraint
changes in Prisma.
```
[ ] Yes
```

Generate a clean migration to sync expected DB state

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Adds a new workflow to be manually run that will promote the staging application in Heroku.
Manually tested.
```
[ ] Yes
```

chore(api): Add Github action to promote staging to production

---

src/versions/versions.controller.spec.ts
src/versions/versions.controller.ts

Forgot to update this guy when I was first getting things functional
```
[ ] Yes
```

/versions POST: use body instead of query param

---

src/influxdb/influxdb.service.spec.ts
src/influxdb/influxdb.service.ts
src/influxdb/interfaces/create-point-options.ts
src/influxdb/interfaces/field.ts
src/telemetry/__snapshots__/telemetry.controller.spec.ts.snap
src/telemetry/dto/field.dto.ts
src/telemetry/dto/write-telemetry-points.dto.ts
src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts

This code change extends the telemetry endpoint to accept several types (booleans, floats, integers, and strings) to more closely match what was done in the [node](https://github.com/iron-fish/ironfish/blob/master/ironfish/src/telemetry/index.ts#L19-L23)
```
[ ] Yes
```

feat(api): Support different point types in telemetry

---

src/users/__snapshots__/users.controller.spec.ts.snap
src/users/dto/update-user.dto.ts

You cannot sign up for a user with an empty graffiti, so you should not be able to update to one either.
Tested locally
```
[ ] Yes
```

Dont allow empty graffiti when updating user

---

src/events/events.service.spec.ts
src/events/events.service.ts

Fetch the events sorted by the time they occurred by default.
Updated unit test.
```
[ ] Yes
```

feat(api): Sort events by `occurred_at` instead of `id`

---

src/users/__snapshots__/users.controller.spec.ts.snap
src/users/dto/update-user.dto.ts
src/users/users.controller.spec.ts

I think the validation doesn't seem to be working correctly when updating users -- it seems like it's canceling validation unless three of the other fields are undefined. I'm trying out making them all optional for now -- it does have the side effect of allowing updates with empty objects, but I think that could be fixed separately.
New API tests should pass.
```
[ ] Yes
```

Make all fields optional on UpdateUserDTO

---

package.json

Since Prisma lacks a clean way to reset a test DB, this adds a `test:clean` command to wipe the DB before tests. This is a bit of a band-aid fix, ideally tests would clean up after themselves, or be idempotent in some way. I'm not in love with this, so if someone thinks it's better to avoid adding this, fine by me.
Apparently an open issue with Prisma with no solution in sight. Other solutions some people have implemented: https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/stdlib/prisma-utils.ts
This adds no measurable time to the test run _yet_. Ran with `time` a few times to compare, both ways took pretty close to exactly 40 seconds.
```
[ ] Yes
```

Add a test clean command to clear DB

---

src/blocks/blocks.service.ts

Remove the creation check when upserting blocks for the chain re-sync.
Manually tested.
```
[ ] Yes
```

feat(api): Temporarily remove `created_at` check for resync

---

src/blocks/blocks.service.ts

Reverts 0c91431d4d60eabf2ccff04d79af171cdbeee05f
N/A
```
[ ] Yes
```

feat(api): Revert `created_at` timestamp check for block upserts

---

src/users/interfaces/serialized-user.ts
src/users/users.controller.spec.ts
src/users/users.service.ts
src/users/utils/user-translator.ts

Return when users were created from API endpoints.
Updated unit tests for get and list endpoints.
```
[ ] Yes
```

feat(api): Return `created_at` for users

---

package.json
src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts
yarn.lock

Since we hit high series cardinality on influx and changed the tags in the version 0.1.23, the API should have a minimum version check before writing any points.
```
[ ] Yes
```

feat(api): Add minimum telemetry version check

---

src/telemetry/__snapshots__/telemetry.controller.spec.ts.snap
src/telemetry/dto/field.dto.ts

Allow 0 values to be written to the telemetry service.
Updated unit test snapshots.
```
[ ] Yes
```

fix(api): Use `Min(0)` instead of `IsPositive` for telemetry fields

---

src/users/dto/update-user.dto.ts
src/users/interfaces/update-user-options.ts
src/users/users-updater.ts
src/users/users.controller.ts
src/users/users.service.spec.ts
src/users/users.service.ts

Allow updates for user GitHub fields.
```
[ ] Yes
[x] No
```

feat(api): Add `github` as an option when updating users

---

src/blocks-transactions-loader/blocks-transactions-loader.spec.ts
src/blocks/blocks.service.ts
src/events/events.jobs.controller.spec.ts
src/events/events.jobs.controller.ts
src/events/events.service.spec.ts
src/events/events.service.ts
src/events/interfaces/delete-block-mined-event-options.ts

Add a method to set the `deleted_at` timestamp on the Events Service and refactor the graphile job to ignore the user id.
```
[ ] Yes
[x] No
```

feat(api): Add delete service method for EventsService

---

package.json
yarn.lock

This reverts commit ab2f6f175e18aad4658b0a84f5216c5a4bac73fe.
```
[ ] Yes
[ ] No
```

Revert "chore(deps): Bump dd-trace from 2.2.0 to 2.2.1 (#673)"

---

src/events/events.service.spec.ts
src/events/events.service.ts

Do not create any block mined events after sequence 150000.
Added unit test.
```
[ ] Yes
[x] No
```

feat(api): Do not create any events after the end of phase one sequence

---

src/blocks/__snapshots__/blocks.controller.spec.ts.snap
src/users/users.service.ts

Fix the previous page cursor in the ranking query to not return the top ranked users.
Manually tested
```
[ ] Yes
[x] No
```

fix(api): Fix pagination for getting previous chunks of users

---

src/app.module.ts
src/auth/auth.controller.ts
src/auth/strategies/magic-link.strategy.ts
src/blocks/blocks.service.ts
src/test/test-app.ts

This allows us to disable logins and auth in the case that we we set an
environment variable called DISABLE_LOGIN. This is useful to help make
phase1 readonly.
https://linear.app/ironfish/issue/IRO-1752/prevent-logging-into-phase-1-api
Write test
```
[ ] Yes
[x] No
```

Disable login if DISABLE_LOGIN env is set

---

prisma/migrations/20220408160724_create_node_uptimes/migration.sql
prisma/migrations/20220408170514_create_node_uptimes/migration.sql
prisma/schema.prisma

Preparation for upcoming changes. We'll have a graphile job check this periodically and update to 0 when the threshold has been hit, telemetry endpoint will update this when it receives a request with the extra graffiti parameter
```
[ ] Yes
[ ] No
```

Add NodeUptime table and migration

---

.env.template
.env.test
src/app.module.ts
src/blocks/blocks.service.spec.ts
src/blocks/blocks.service.ts
src/test/test-app.ts

We check for user creation timestamps with block mined events. This PR wraps that check with an environment variable to make re-syncs easier.
Added unit tests.
```
[ ] Yes
[x] No
```

feat(api): Add `CHECK_USER_CREATED_AT` when upserting block mined events

---

src/graphile-worker/graphile-worker.service.ts
src/user-points/user-points.controller.spec.ts
src/user-points/user-points.controller.ts
src/user-points/user-points.jobs.controller.spec.ts

Some jobs have no payloads, and we shouldn't need to pass undefined as
not passing anything is the same as passing undefined bound to that
variable.
Ran tests
```
[ ] Yes
[x] No
```

Make payload in addJob() optional

---

src/node-uptimes/node-uptimes.module.ts
src/node-uptimes/node-uptimes.service.spec.ts
src/node-uptimes/node-uptimes.service.ts
src/telemetry/dto/write-telemetry-points.dto.ts
src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts
src/telemetry/telemetry.rest.module.ts

When the API receives a telemetry write request, and the graffiti is included in the request payload, we want to track that as a NodeUptime "check-in" in the DB. We only want to up date the check-in count once per hour.
```
[ ] Yes
[ ] No
```

Implement NodeUptime tracking on telemetry endpoint

---

.github/pull_request_template.md

This is an oppinionated change but I noticed the front end doesn't have
it, and I just have to check NO for every PR. It'll be nice not to have
to do that I think.
```
[ ] Yes
[x] No
```

Remove no from breaking change in PR template

---

src/common/enums/metrics-pool.ts
src/events/events.controller.ts
src/events/events.service.ts
src/users/interfaces/serialized-user-metrics.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts

This adds new pool ranks based off of the pool categories the pool
ranks.
Wrote tests and checked the API using prod data
```
[ ] Yes
[x] No
```

Add pool ranks to metrics endpoint

---

src/users/interfaces/serialized-user-metrics.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts

They just weren't being sent back, but now they are. I also fixed tests to actually test for the 0 points because it should be 0.
Ran tests
```
[ ] Yes
```

Send back node uptime in user metrics

---

src/users/users.service.ts

listWithRank is the only method that uses this, and the metadata isn't
some extra thing, it's the basic pagination data. Also I think these
queries can be removed entirely in Postgres using count() queries or
just basic assumption about leaderboard containing all users.
Run same tests, no code change.
```
[ ] Yes
```

Merge getListWithRankMetadata into listWithRank

---

src/common/utils/enums.ts
src/users/dto/users-query.dto.ts
src/users/dto/validators.ts
src/users/interfaces/list-by-rank-options.ts
src/users/interfaces/list-users-options.ts
src/users/users.controller.ts
src/users/users.service.spec.ts
src/users/users.service.ts

The old leaderboard only took 1 single event type, now it takes multiple
event types which it then filters the leaderboard on. I'm not sure if this is
the only place this needs to be changed, but the user metrics was also
changed to reflect this.
TODO: Run and adjust leaderboard test.
```
[ ] Yes
```

Change Leaderboard query to take event types

---

src/users/interfaces/serialized-user-metrics.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts
src/users/users.rest.module.ts

In user lifetime metrics, send back their NodeUptimes data now.
Adjusted tests
```
[ ] Yes
```

Return NodeUptimes in user metrics

---

src/users/interfaces/serialized-user-metrics.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts

Exposing this now
Run tests and hit the API manually
```
[ ] Yes
```

Add SEND_TRANSACTION to user metrics API

---

src/node-uptimes/node-uptimes.jobs.controller.ts
src/node-uptimes/node-uptimes.module.ts
src/node-uptimes/node-uptimes.service.spec.ts
src/node-uptimes/node-uptimes.service.ts
src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts

I did this because I'm starting to see an issue with our code base in
that it's not clear who owns what responsibility, and I see a lot of
code fragmentation. I'm not sure what to do about it, though I just feel
like a "NodeUptime" service should be in charge of also creating or
scheduling the creation of the event it's related to.
```
[ ] Yes
```

Move event scheduling into uptime service

---

src/blocks/blocks.controller.spec.ts

This test sometimes updates snapshots and throws a different validation error since the API validates for a positive size.
Ran unit tests.
```
[ ] Yes
```

test(api): Add minimum to mocked size in blocks controller

---

prisma/migrations/20220426235432_add_send_transaction_to_user_points/migration.sql
prisma/schema.prisma
src/user-points/user-points.service.spec.ts
src/user-points/user-points.service.ts

The UserPoints object will be used to cache aggregated events data for faster retrieval from the API. For example, total points for a user and total points for a user in a given category. This PR adds support for aggregating the new `SEND_TRANSACTION` event for Phase 2
Unit tests
```
[ ] Yes
```

Aggregate SEND_TRANSACTION events on UserPoints

---

src/events/events.service.spec.ts
src/events/events.service.ts
src/user-points/user-points.service.spec.ts
src/user-points/user-points.service.ts

When events are deleted, the UserPoints aggregate model is not
deleted. This causes the aggregate table to now be updated when an event
is deleted.
I wrote a test
```
[ ] Yes
```

Update user points on event deletion

---

prisma/migrations/20220504205045_add_deposits_head_table/migration.sql
prisma/schema.prisma
src/events/deposits.controller.spec.ts
src/events/deposits.controller.ts
src/events/deposits.service.ts
src/events/dto/upsert-deposit.dto.ts

We need to track blocks that do not have deposits in them as well as deposits. This is so the transaction sync process can restart from a block that does not have deposits in it.
Unit tests
```
[ ] Yes
```

Track deposits head

---

src/events/events.controller.spec.ts
src/events/events.service.spec.ts
src/events/events.service.ts
src/node-uptimes/node-uptimes.jobs.controller.spec.ts
src/node-uptimes/node-uptimes.service.spec.ts
src/telemetry/telemetry.controller.spec.ts
src/users/users-updater.spec.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts
src/users/users.rest.module.ts
src/users/users.service.spec.ts
src/users/users.service.ts
src/users/utils/user-translator.ts

We can remove `users.total_points` since we have materialized values in `user_points`. Before removing that column, we should migrate existing reads to use the new table.
```
[ ] Yes
```

feat(api): Pull `total_points` from `user_points`

---

src/events/dto/upsert-deposit.dto.ts

Allow empty blocks to be uploaded for deposits. We need to track empty blocks so the syncer knows where to start syncing from
```
[ ] Yes
```

allow empty deposit blocks

---

src/events/deposits.controller.ts

The `deposits/head` endpoint does not need to be protected by an API Key
```
[ ] Yes
```

remove api key from deposits head

---

src/events/events.service.ts

Metadata wasn't being materialized for events with deposits
```
[ ] Yes
```

Fix deposit metadata

---

src/common/constants.ts
src/events/deposits.controller.spec.ts

Based on a conversation in slack to adjust the point economy.
Run  tests
```
[ ] Yes
```

Reduce send_transaction points down to 1 points

---

src/events/deposits.upsert.service.ts

Since these are inside a transaction block, they should be using the transaction's instance of prisma to ensure the db transaction is happening correctly
```
[ ] Yes
```

Use the transaction instance of prisma for deposits upsert

---

src/events/events.service.ts
src/users/users.controller.ts

The API is not returning the correct rank for Pool 1 ranks. This code change:
* Adds the `SEND_TRANSACTION` event type
* Fixes some minor formatting for consistency
* Queries explicit columns from `user_ranks`
Manual tests and existing unit tests.
```
[ ] Yes
```

fix(api): Properly return main pool ranks

---

src/blocks/blocks.service.spec.ts
src/blocks/blocks.service.ts

The Prisma client [panics](https://github.com/prisma/prisma/issues/10586) on large numbers (> 64 bit). This code change checks for the sequence being passed when querying blocks.
Unit test
```
[ ] Yes
```

fix(api): Restrict `search` parameter in `/blocks`

---

src/events/events.service.spec.ts
src/events/events.service.ts

We don't need a transaction when getting event type ranks
N/A
```
[ ] Yes
```

fix(api): Don't use transaction when reading ranks

---

src/events/deposits.controller.spec.ts
src/events/deposits.upsert.service.ts

When we are syncing deposits to the Iron Bank the API listens to events coming from the syncer. There are 3 types of events
- Connected => when a new block is added to the main chain
- Disconnected => when a block is removed from the main chain (in the process of switching to another heavier chain)
- Fork => when a new block is added to a fork that is not the heaviest chain
We should not care about Fork operations because any transaction made on a fork will not be counted as a deposit. If that fork eventually becomes the heaviest chain then there will be a Connected  event emitted for that block eventually and the transaction will be picked up there.
Descriptions of the event types are in code [here](https://github.com/iron-fish/ironfish/blob/staging/ironfish/src/blockchain/blockchain.ts#L …

Ignore FORK operations when creating deposits and events

---

.github/workflows/ci.yml

To handle PRs that are submitted via a forked repo we should trigger CI to re-run on the `pull_request` event
```
[ ] Yes
```

Trigger CI on pull reuqest actions

---

src/events/events.service.ts
src/graphile-worker/graphile-worker.service.ts
src/graphile-worker/interfaces/graphile-worker-job-options.ts

We have a large number of update_latest_points graphile jobs queued in prod. Many of them are duplicates which we can improve by not adding duplicate jobs into the queue using a [jobKey](https://github.com/graphile/worker#replacing-updating-and-removing-jobs). Also this removes the `queueName` parameter. `queueName` is used when jobs need to be [executed synchronously in a queue](https://github.com/graphile/worker#parsedcronitems). For these jobs we do not require that so maybe removing this will help speed them up as well.
Unit tests
```
[ ] Yes
```

Improve performance on update_latest_points graphile job

---

src/events/events.service.spec.ts
src/events/events.service.ts

Use the materialized table for ranking instead of performing aggregations on `events`.
Manual testing + staging testing
```
[ ] Yes
```

feat(api): Use `user_points` when fetching event type ranks

---

src/events/events.service.spec.ts
src/events/events.service.ts
src/node-uptimes/interfaces/create-node-uptime-event-options.ts
src/node-uptimes/node-uptimes-loader.module.ts
src/node-uptimes/node-uptimes-loader.spec.ts
src/node-uptimes/node-uptimes-loader.ts
src/node-uptimes/node-uptimes.jobs.controller.spec.ts
src/node-uptimes/node-uptimes.jobs.controller.ts
src/node-uptimes/node-uptimes.jobs.module.ts
src/node-uptimes/node-uptimes.service.spec.ts
src/node-uptimes/node-uptimes.service.ts
src/telemetry/telemetry.controller.spec.ts

* Enqueue `NODE_UPTIME` graphile job out of Prisma transaction
* Create `NodeUptimesLoader` to remove coupling between ORM and worker controller
* Add credit hour check to graphile job (was only in transaction from service before)
* Add `occurredAt` to payloads to account for worker delays
* Remove unused `added` return value
Unit tests
```
[ ] Yes
```

feat(api): Move node uptimes job out of transaction

---

src/events/events.service.spec.ts
src/events/events.service.ts

Total point aggregates on `user_points` are not taking into account `NODE_UPTIME` and `SEND_TRANSACTION`.
Unit tests
```
[ ] Yes
```

fix(api): Add `NODE_UPTIME` and `SEND_TRANSACTION` aggregates in refresh

---

src/events/events.service.ts

See title
https://linear.app/ironfish/issue/IRO-1959/ensure-occurredat-is-always-a-date-instance
Manually ran node and verified uptime events against local API
```
[ ] Yes
```

fix(api): Ensure `occurredAt` is a `Date` instance at runtime

---

src/api-config/api-config.service.ts
src/prisma/prisma.service.ts

There is a read replica now set up on production. This code change uses a new client to perform aggregations and rankings to reduce CPU load on the main machine.
Manually ran against read replica URL.
```
[ ] Yes
```

feat(api): Add read client for ranking queries

---

src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts
src/telemetry/telemetry.rest.module.ts
src/versions/versions.service.spec.ts
src/versions/versions.service.ts

This will help incentivize users to run the latest version by only giving credit for node uptime for nodes running the latest version (with a 1 week grace period).
Note that we should probably announce we're making this change before we merge/deploy this, so that users have time to upgrade their nodes appropriately.
Potential alternatives:
- Bigger rolling window on the grace period (2 weeks). This seems fairly reasonable, if we feel 1 week is too aggressive
- Set the version in a config variable. This feels fine, with the added caveat that we have to remember to update it and announce when we do
- Other? Open to suggestions
```
[ ] Yes
```

Limit nodes that get credit for uptime by the latest version with a 1 week grace period

---

src/blocks-transactions-loader/blocks-transactions-loader.ts
src/transactions/transactions.controller.spec.ts
src/transactions/transactions.controller.ts
src/transactions/transactions.service.spec.ts
src/transactions/transactions.service.ts

There are many reasons why we may want to see transactions that are not associated with a block in the block explorer. The use case driving this change is that when the pool tries to make a payout we want to be able to show the transaction before it's added to a block. Being able to view them in the block explorer would give more insight on when they get sent out and if they expire. We also could use them to create a mempool explorer in the future
Unit tests
```
[ ] Yes
```

add bulk upload transactions endpoint

---

.env.template
.env.test
src/app.module.ts
src/graphile-worker/graphile-worker.microservice.ts
src/test/test-app.ts

Allow environment variable configuration for Graphile Worker concurrency.
N/A
```
[ ] Yes
```

feat(api): Add concurrency configuration for Graphile

---

.github/CODEOWNERS

We renamed the engineering group, so update the CODEOWNERS for this repository.
N/A
```
[ ] Yes
```

chore(api): Fix CODEOWNERS to use `@iron-fish/engineering`

---

src/graphile-worker/graphile-worker.service.ts

There is a race condition here if initWorkerUtils() is called multiple
times in parallel.
Run tests
```
[ ] Yes
```

Fix graphile WorkerUtils race condition

---

src/events/events.service.ts

We don't need to use a transaction for this heavy aggregation.
N/A
```
[ ] Yes
```

fix(api): Remove aggregation from user point update transaction

---

src/events/deposits.upsert.service.ts
src/health/health.controller.spec.ts
src/health/health.controller.ts
src/health/health.rest.module.ts

- queries deposits and blocks tables to count deposits where either the block
hash does not exist in blocks or there is a mismatch in 'main'
- adds DepositUpsertService to HealthController to expose mismatched deposits
count
```
[ ] Yes
```

exposes mismatched deposits count in admin health check

---

src/blocks-transactions-loader/blocks-transactions-loader.ts
src/blocks-transactions/blocks-transactions.service.spec.ts
src/blocks-transactions/blocks-transactions.service.ts
src/transactions/transactions.service.spec.ts

Transactions should be returned in index order to be correct. This now
stores the index, and results them in index order.
Added tests
```
[ ] Yes
```

Preserve transaction index and sort by them

---

src/events/deposits.upsert.service.ts

refreshDeposit will set deposits.main to false for any deposit without a block
in blocks. however, the queries that identify mismatched deposits will still
surface those deposit records as mismatches even after that update. these
changes treat deposits without blocks as mismatches only if they are marked as
being on the main chain.
```
[ ] Yes
```

only considers deposits without blocks mismatched if marked as main

---

src/events/deposits.upsert.service.spec.ts
src/events/deposits.upsert.service.ts

- uses deposit object as payload instead of nesting within another object
- amends unit tests to set expectations on the fiels of the payload object
- synced blocks and deposits to local API
- created mismatched deposits in local DB
- ran /deposits/refresh locally, observed successful jobs
```
[ ] Yes
```

fixes the payload for REFRESH_DEPOSIT graphile worker jobs

---

src/events/events.service.spec.ts
src/events/events.service.ts

concurrent jobs are contending with one another and with UPSERT_DEPOSIT jobs for
access to the `events` table. limiting concurrency may help to reduce the error
rate and to reduce the time each job spends waiting to acquire a transaction
lock.
- adds queues for UPDATE_LATEST_POINTS jobs
- each job randomly added to one of four queues
- updated unit tests
```
[ ] Yes
```

limits concurrency of UPDATE_LATEST_POINTS jobs

---

src/events/events.service.spec.ts
src/events/events.service.ts
src/graphile-worker/interfaces/graphile-worker-job-options.ts

a large percentage of `UPDATE_LATEST_POINTS` jobs share the same jobKey. the
jobKey prevents duplicate jobs from being queued, but jobs for some users and
event types are queued so frequently that there is almost always one in the
queue.
- sets runAt to defer job execution by 10 minutes
- adds jobKeyMode argument to addJob
- uses jobKeyMode=preserve_run_at to throttle jobs with the same jobKey
- updated unit tests
```
[ ] Yes
```

throttles UPDATE_LATEST_POINTS for each job key

---

src/graphile-worker/graphile-worker.service.ts

- without this change jobKeyMode is not set when a job is enqueued
```
[ ] Yes
```

passes jobKeyMode argument through to workerUtils

---

src/events/deposits.upsert.service.ts
src/events/events.service.ts

- changes behavior of `EventsService.createWithClient` to revive previously
soft-deleted events. this un-soft-deletes events from blocks or transactions
re-orged back onto the main chain.
- updates refreshDeposits to find cases where events.deleted_at is null but
deposits.main is true
```
[ ] Yes
```

sets deleted_at to null when upserting events

---

src/events/deposits.upsert.service.ts

enqueues a maximum of 50000 jobs
```
[ ] Yes
```

limits the number of deposits to fix in each call to /deposits/refresh

---

src/events/events.service.ts

I am fixing an issue with API performance on the Users page as described in https://github.com/iron-fish/website-testnet/issues/271 for users with a large number of events.
Cursor paginating (in Prisma implementation) is becoming very heavy for many entries since it fetches all available rows from DB and limits the result on the client side.
Proposed changes query DB almost in the same way cursor pagination is intended to work, including `limit` in the SQL query.
See performance for `/events` route:
Before changes - ~6sec:
After - ~440ms:
UPD:
`/metrics` route also was performing poorly on a big amount of events:
Before:
After:
Tests are passing without changes
```
[ ] …
```

Fix performance of Events list

---

.github/dependabot.yml

Allows us to minimize time spent on looking at/merging updates a little bit
```
[ ] Yes
```

Set dependabot to only update once a week

---

src/telemetry/telemetry.controller.ts

We are running up against InfluxDB usage limits. There are some measurements we are not using currently but still want to keep in telemetry so we don't have to do another release if we remove them. This allows us to keep them in telemetry but not upload to influx
```
[ ] Yes
```

Add ability to skip measurements in telemetry

---

src/telemetry/dto/write-telemetry-points.dto.ts
src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts

This whitelists all telemetry points. If you want telemetry in here,
you'll need to submit a code review after you submit it to the node
to let it through into our influx instance.
Likewise, we now only let every 5th block_propagation block sequence
point through.
Run new tests, and watch our influx dashboard.
```
[ ] Yes
```

Add telemetry whitelisting

---

src/blocks-transactions-loader/blocks-transactions-loader.module.ts
src/blocks-transactions-loader/blocks-transactions-loader.ts
src/events/events.service.ts

Try to not queue `DELETE_BLOCK_MINED_EVENT` and `UPSERT_BLOCK_MINED_EVENT` if these events are disabled at the current block height.
None
```
[ ] Yes
```

Don't queue mined block events unless its enabled

---

src/telemetry/telemetry.controller.ts

Adds individual network message types to telemetry whitelist.
Run tests, and watch influx dashboard.
```
[ ] Yes
```

Add network message types to telemetry whitelist

---

src/telemetry/telemetry.controller.ts

Adds RSS metric to telemetry whitelist
Run tests, and watch influx dashboard.
```
[ ] Yes
```

Add RSS metric to telemetry whitelist

---

src/telemetry/telemetry.controller.ts

Whitelist `forks_count` metric in telemetry.
```
[ ] Yes
```

Whitelist forks_count metric in telemetry

---

src/events/deposits.upsert.service.ts

Fixes influx datapoint bug (ORE was being reported, not IRON)
```
[ ] Yes
```

fix: adjust calculation for influx to calculate iron, not ore

---

src/events/events.service.ts
src/node-uptimes/node-uptimes.service.ts
src/prisma/prisma.service.ts
src/user-points/user-points.service.ts

I'm not totally sure that this will be helpful, but this change moves the aggregation and counts used when calling /user/metrics over to the read replica. Those queries 
were often timing out on the primary, so it might reduce the load.
```
[ ] Yes
```

Move some aggregations and counts over to the read replica

---

src/blocks-transactions/blocks-transactions.service.ts
src/blocks/blocks.service.ts
src/events/deposits.service.ts
src/events/events.service.ts

Using the read client for the metrics endpoint has generally improved the response time of the user profile page on the testnet site, but the events endpoint is still timing out from time to time. Let's try moving that query over as well.
```
[ ] Yes
```

Use read client for events endpoint

---

src/events/events.service.ts

This should take some CPU load off the master DB, with the caveat that we might be aggregating incorrect events if the writes haven't propagated yet. However, we can just recalculate everyones points at some interval to make sure we fix up any missing points.
```
[ ] Yes
```

Use read only slave for updating user points

---

prisma/migrations/20221101163714_drop_deleted_at_from_events/migration.sql
prisma/schema.prisma
src/events/deposits.upsert.service.spec.ts
src/events/events.service.spec.ts
src/events/events.service.ts

We're not using `deleted_at` and soft deletes are a scam, so we can drop this column. I'll delete all the unused records from production before deploying.
Existing unit tests
```
[ ] Yes
```

feat(api): Drop `events.deleted_at`

---

src/events/events.service.spec.ts
src/events/events.service.ts
src/user-points/interfaces/upsert-user-points-options.ts
src/user-points/user-points.jobs.controller.spec.ts
src/user-points/user-points.service.spec.ts
src/user-points/user-points.service.ts
src/users/users.controller.ts

Updates graphile job to update `count` as well as `points`
Also makes `metrics` endpoint query use the value stored in DB rather than redoing aggregation.
unittest
```
[ ] Yes
```

feat: points graphile job update, metrics api query counts cache

---

src/events/events.service.spec.ts
src/events/events.service.ts
src/users/users.controller.ts

We can now avoid aggregating the events table completely using user_points, especially since this doesn't even return the rank. This removes 7 aggregations over the events table.

Optimize life time metrics to use user_points table

---

src/blocks-transactions-loader/blocks-transactions-loader.ts

Were dying at 20 seconds. We need more time.
```
[ ] Yes
```

Increase timeout for uploading blocks from the syncer

---

prisma/migrations/20221108061036_add_index_to_deposits/migration.sql
prisma/schema.prisma
src/events/deposits.upsert.service.spec.ts
src/events/deposits.upsert.service.ts
src/events/events.service.ts
src/users/users.service.ts

Converts this code path to use many bulk creation strategies instead
of upserting one at a time in the block.
I pulled down production DB and ran it locally. Takes about 4s per 300 TX instead of 40 seconds.
```
[ ] Yes
```

Optimizes DepsoitsUpsertService.upsert()

---

src/events/events.service.spec.ts
src/events/events.service.ts
src/node-uptimes/node-uptimes-loader.spec.ts
src/node-uptimes/node-uptimes-loader.ts
src/node-uptimes/node-uptimes.jobs.controller.ts
src/node-uptimes/node-uptimes.service.spec.ts
src/node-uptimes/node-uptimes.service.ts

This limits CREATE_NODE_UPTIME_EVENT jobs to 1 per user instead of 1 queue per user, and many jobs per user.
```
[ ] Yes
```

fix: Limit CREATE_NODE_UPTIME_EVENT to 1 per user

---

src/events/deposits.upsert.service.spec.ts
src/events/deposits.upsert.service.ts

This fixes a very serious API bug that will change the main chain status of all deposits if a deposit comes through with no users found in the DB.
Added tests, then fixed the bug.
```
[ ] Yes
```

Fix upsert updating all deposits when no users

---

package.json
src/graphile-worker/graphile-worker.microservice.ts
yarn.lock

We cannot run even a single worker without destroying the entire database. It's reproducable locally. One call to get_jobs completely freezes the DB. Graphile has a large large large performance boost in 14 but its only in alpha, https://github.com/graphile/worker/pull/274 with the discussion here: https://github.com/graphile/worker/issues/240
I tested this locally with the production DB before upgrading this.
```
[ ] Yes
```

Upgrade graphile to alpha 14

---

src/node-uptimes/node-uptimes.jobs.controller.ts

It's now coming back in graphile 14 as a string instead of a date
```
[ ] Yes
```

Fix occured at serializing as a string

---

prisma/migrations/20221122194723_deposit_amount_bigint/migration.sql
prisma/schema.prisma

Bigint for amount
```
[ ] Yes
```

fix: bigint for deposit amount in postgres

---

prisma/migrations/20221125025815_change_number_type_transaction_fee/migration.sql
prisma/schema.prisma

A 32 bit integer is not enough to store the fee.
```
Error occurred during query execution: ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(3), cause: Some(Error { kind: ConversionError("Unable to fit integer value '-4140884682' into an INT4 (32-bit signed integer)."), original_code: None, original_message: None }) }) })
at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:34314:13)
at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:34293:12)
at async PrismaService._request (/app/node_modules/@prisma/client/runtime/index.js:35273:16)
at async TransactionsService.createManyWithClient (/app/build/transactions/transactions.service.js:32:9)
at async prisma.$transaction.timeout …
```

Change Transaction.fee to float (64bit float)

---

src/events/deposits.upsert.service.ts

This query takes 10 minutes to run.. slow it down and also run it on the read slave.
```
[ ] Yes
```

Change submit deposited job to run on read

---

src/events/events.service.ts
src/events/interfaces/serialized-event-metrics.ts
src/users/users.controller.spec.ts
src/users/users.service.spec.ts
src/users/users.service.ts

1. Excludes users from rank list if they have 0 points
2. When user is searched for, return users even if they have no points
3. Lifetime points should return 0 for user (without rank query) if user has no points.
Unittest
```
[ ] Yes
```

feat: exclude users from rankings that have 0 points

---

src/users/dto/user-query.dto.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts

This was removed in the front end
Review with https://github.com/iron-fish/ironfish-api/pull/1144/files?diff=split&w=1
```
[ ] Yes
```

Remove rank from users/find and users/[id]

---

src/user-points/user-points.jobs.controller.ts

Javascript date constructor for January is `0` not `1` 🤦 
Discovered this bug by looking at query log in local environment when calling endpoint. Query that was being run on POOL4 refresh was:
```
SELECT SUM("points"),
COUNT("points"),
MAX("occurred_at")
FROM
(SELECT "public"."events"."points",
"public"."events"."occurred_at"
FROM "public"."events"
WHERE ("public"."events"."type" = 'MULTI_ASSET_MINT'
AND "public"."events"."user_id" = '2'
AND "public"."events"."occurred_at" >= '2023-02-01 08:00:00'
AND "public"."events"."occurred_at" < '2023-01-12 16:27:34.129')
OFFSET '0') AS "sub"
```
```
[ ] Yes
```

fix: bug in date filter for pool4 refresh

---

src/events/events.module.ts
src/events/events.service.ts
src/events/multi-asset.service.spec.ts
src/events/multi-asset.service.ts

Enriching block hash and transaction hash directly from `multi_asset` model.
```
[ ] Yes
```

fix: link multiasset to blocks

---

src/telemetry/telemetry.controller.ts

See title. 
[This accompanying PR](https://github.com/iron-fish/ironfish/pull/3147) in the `ironfish` repo pushes the `create_new_block_template_duration` measurement to the API. 
Build successful
```
➜  ironfish-api git:(holahula/feat/influx-block-template-support) yarn build
yarn run v1.22.19
$ tsc -b
✨  Done in 2.05s.
```
```
[ ] Yes
```

feat(api): Add new block template construction duration measurement to Influx whitelist

---

src/main.ts

We don't need this cap since we manually tweak this number to try to max the CPU usage and database usage.
```
[ ] Yes
```

Remove worker limits capped by CPU

---

src/asset-descriptions/asset-descriptions.controller.spec.ts
src/asset-descriptions/asset-descriptions.controller.ts
src/asset-descriptions/asset-descriptions.rest.module.ts
src/asset-descriptions/interfaces/serialized-asset-description.ts
src/asset-descriptions/utils/asset-descriptions.translator.ts

Return associated block timestamps for asset transactions
Unit tests
```
[ ] Yes
```

feat(api): Return timestamps for asset descriptions

---

prisma/migrations/20230222171607_add_faucet_index/migration.sql
prisma/schema.prisma
src/faucet-transactions/faucet-transactions.service.ts

This API is an optional debugging API. I'm moving it to the read only client, removing the transaction (since its on a follower anyway).
Data dog is showing this as the second slowest API, because the table is growing very large.
```
count: 339645
completed: 339647
```
Slowest DB Query
```
SELECT "public"."faucet_transactions"."id",
"public"."faucet_transactions"."created_at",
"public"."faucet_transactions"."updated_at",
"public"."faucet_transactions"."email",
"public"."faucet_transactions"."public_key",
"public"."faucet_transactions"."started_at",
"public"."faucet_transactions"."completed_at",
"public"."faucet_transactions"."tries",
"public"."faucet_transactions"."hash"
FROM "public"."faucet_transactions"
WHERE ("public"."faucet_transactions"."started_at" IS NOT NULL
AND …
```

Add an index to faucet and remove transaction

---

src/telemetry/telemetry.controller.ts
src/telemetry/telemetry.rest.module.ts
src/versions/versions.service.ts

Changes the `POST: /telemetry` endpoint to pull data from read replica when:
1) Looking up user graffiti
2) Looking up version
Tests pass
```
[ ] Yes
```

fix: makes read calls where possible for telemetry endpoint

---

src/common/constants.ts
src/events/multi-asset.upsert.service.spec.ts
src/events/multi-asset.upsert.service.ts
src/telemetry/telemetry.controller.ts

* Check block timestamp for multi asset events
* Don't count online events after phase 3 end
```
[ ] Yes
```

feat(api): Check phase 3 when upserting multi asset events

---

src/users/interfaces/serialized-user-metrics.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts

Return cached values from previous pools in metrics request.
I chose to add a new field to the response instead of updating the existing `pools` field because the testnet UI is using that and it felt weird to set the count to NULL since that value isn't populated. It seemed cleaner to just return just the points altogether, but open to changing.
Unit test
```
[ ] Yes
```

feat(api): Return pool points

---

src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/redemptions/redemption.service.ts

This will always return can_attempt in get kyc endpoint
```
[ ] Yes
```

Always return can_attempt in get redemption

---

src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/utils/serialize-kyc.ts
src/redemptions/redemption.service.ts

This will not send back if you can attempt a KYC flow, now it will send back if you are eligible.
```
[ ] Yes
```

Send back eligibility in can_attempt

---

src/user-points/user-points.jobs.controller.spec.ts
src/user-points/user-points.jobs.controller.ts

If a previous phase throws an error, retry the job when refreshing
Unit test
```
[ ] Yes
```

feat(api): Throw errors from previous APIs when refreshing

---

src/jumio-transactions/jumio-transaction.service.spec.ts
src/jumio-transactions/jumio-transaction.service.ts

This is the only highly sensitive PII we need to scrub before saving the workflow retrieve information.
tests pass
```
[ ] Yes
```

feat: scrub PII from extractions when saving Jumio transactions

---

src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-kyc/fixtures/image-check.ts
src/jumio-kyc/fixtures/workflow.ts
src/jumio-kyc/kyc.service.ts
src/jumio-transactions/jumio-transaction.service.ts
src/redemptions/redemption.module.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

When a user submits a KYC attempt, if they fail they will be flagged in subsequent transactions as duplicate face detected.
Here we check to make sure all duplicate faces that are detected are associated with users account associated with the current callback context.
Tests pass
```
[ ] Yes
```

feat: allow repeated face error if the repeated face is from same user

---

prisma/migrations/20230308230847_add_pool_allocation_columns/migration.sql
prisma/schema.prisma

Adds allocations table, I am planning on calculating this via graphile job that will be triggered by protected endpoint. If the allocations exist, I will throw error and require user to wipe table manually if they want to regenerate.
```
[ ] Yes
```

feat: add allocations table

---

src/redemptions/redemption.service.ts

Raises ban logic ahead of enabled KYC error so that we can start to see if there are any spurious bans.
Tests pass
```
[ ] Yes
```

chore: make ban logic return first

---

src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-kyc/fixtures/watch-list.ts
src/jumio-kyc/fixtures/workflow.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.service.spec.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

1. If the user has `searchResults!==0` returned OR jumio has an `ALERT` label on one of the watchlist entries we fail the user indefinitely for KYC.
2. If the whole workflow is successful now, we can move user to `SUCCESS` label rather than `SUBMITTED`
Tests pass
```
[ ] Yes
```

feat: watchlist screening success/failure integration

---

src/redemptions/redemption.service.ts

Multiface failures resulting from the same jumio account id should not be banned or considered.
This should have been updated with:
https://github.com/iron-fish/ironfish-api/pull/1336
tests pass
```
[ ] Yes
```

fix: success on duplicate faces within an account

---

src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

When there is a failure to run the screening check, there are optional fields missing from response (that were not labeled optional in API specification).
Example failure/response payload:
```
"watchlistScreening": [
{                                                                                                                                                                                          
"id": "94362ecf-9a9d-408b-9f09-3db3d4315a4a",                                                                                                                                          
"data": {                                                                                                                                                                              
}, …
```

fix: remove validation on screen number

---

src/jumio-api/interfaces/jumio-put-standalone-screening.ts
src/jumio-api/interfaces/jumio-standalone-screening-create.ts
src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-api/jumio-api.service.spec.ts
src/jumio-api/jumio-api.service.ts
src/jumio-kyc/fixtures/jumio-create-response.ts
src/jumio-kyc/fixtures/watchlist-create-response.ts
src/jumio-kyc/fixtures/watchlist-put-response.ts
src/jumio-kyc/fixtures/watchlist-upload-response.ts
src/jumio-kyc/fixtures/workflow-watchlist-pass.ts
src/jumio-kyc/fixtures/workflow-watchlist.ts
src/jumio-kyc/fixtures/workflow.ts
src/jumio-kyc/interfaces/screening-data.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/kyc.rest.module.ts
src/jumio-kyc/kyc.service.spec.ts
src/jumio-kyc/kyc.service.ts
src/jumio-transactions/jumio-transaction.service.spec.ts
src/jumio-transactions/jumio-transaction.service.ts
src/redemptions/redemption.service.ts

1. Adds endpoint for manually triggering standalone sanction screening workflows by userId.
2. Adds a method to create/submit standalone screening
a. POST: Create new workflow (10010) with existing `accountId`
b. GET: Retrieve PII from Jumio hosted workflow
b. POST:  push search data (name, dob, country) to workflow from 2a
c. PUT: force search initiation 
4. Callback will optionally run `redemption.calculateStandaloneSanctionStatus` if the workflow for the callback was `10010`
tests pass
NOTE: I tested this via true integration locally and it worked.
```
[ ] Yes
```

feat: add new sanction screening manual trigger endpoint (3/3)

---

src/jumio-api/jumio-api.service.ts

Callback run from standalone watchlist workflow (10010) does not have extractions in it, so this fails.
```
[ ] Yes
```

fix: only santizes extractions if they are in object

---

src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-api/jumio-api.service.spec.ts
src/jumio-api/jumio-api.service.ts
src/jumio-kyc/fixtures/workflow-watchlist-pass.ts
src/jumio-kyc/fixtures/workflow-watchlist.ts
src/jumio-kyc/fixtures/workflow.ts
src/jumio-kyc/kyc.service.ts

Workflow definition key returned as string, not number
tests pass
```
[ ] Yes
```

fix: workflow definition key returned as string

---

src/jumio-api/jumio-api.service.spec.ts
src/jumio-api/jumio-api.service.ts
src/jumio-kyc/fixtures/workflow.ts

Jumio returns `N/A` for first name of a Chinese customer, but then does not accept `N/A` in the parts upload. I have tested manually with removing `N/A` and the screening runs successfully.
Tests pass
```
[ ] Yes
```

fix: fix bug standalone watchlist screening for chinese user data

---

src/redemptions/redemption.service.ts

Removes terminal failures on failed statuses. These users will likely fail out due to max attempts reached.
test pass
```
[ ] Yes
```

feat: remove terminal failures on label status checks

---

src/redemptions/redemption.service.ts

We are currently using eligibility to determine if the user is eligible for KYC in general. If we don't provide explicit case for submitted/success the other checks may erroneously return false.
tests pass, related pr: 
https://github.com/iron-fish/ironfish-api/pull/1340
```
[ ] Yes
```

fix: bug in display success vs deadline

---

src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-kyc/fixtures/liveness-check.ts
src/jumio-kyc/fixtures/workflow.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

We have a list of labels that are considered passable when there are no other failures present.
1. Duplicate face will occur if user has previous KYC attempt that has failed (even for same account).
2. Liveness undetermined is an added check to make sure photograph was not use for face detection, if it can't complete successfully it will give status: `LIVENESS_UNDETERMINED`, which is non-block per Jumio reps. We were told below `risk` of 50, we can disregard this warning.
Tests pass
```
[ ] Yes
```

feat: allow liveness warnings to pass on low risk KYC

---

prisma/migrations/20230314170724_add_age_to_redemption/migration.sql
prisma/schema.prisma
src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-api/jumio-api.service.spec.ts
src/jumio-kyc/fixtures/extraction-check.ts
src/jumio-kyc/fixtures/workflow.ts
src/jumio-kyc/kyc.service.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

Two things:
1. On callback, KYC attempt is marked `TRY_AGAIN` with failure message telling user is below age requirement
2. On eligibility check, users can be eligible to attempt if age is below requirement, but warned their parents must be custodian (will be set to `TRY_AGAIN` if kyc is attempted).
Backfill script (very slow response, no need to rate limit):
```python
import requests
tsv = 'passed_users.tsv'
out = 'output.txt'
token = ''
def retrieve_age():
base_url = "https://retrieval.amer-1.jumio.ai/api/v1/accounts/{}/workflow-executions/{}"
headers = {
'Accept': 'application/json',
'Content-Type': 'application/json',
'User-Agent': 'IronFish Website/v1.0',
'Authorization': f'Basic {token}'
}
num = 0
data = []
with open(tsv) as f:
for row in f.readlines():
print(row.split()) …
```

feat: make KYC unsuccessful if age below 18

---

jest.config.js
src/health/health.controller.spec.ts
src/test/setup.ts

DB data shouldn't bleed between test suites, this makes sure that doesn't happen.
tests pass
```
[ ] Yes
```

chore: reset db at start of each test file

---

src/common/constants.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

We have consolidated all deadlines to the same value, removing the logic here for separate deadlines.
tests pass
```
[ ] Yes
```

fix: remove separate deadlines for pools kyc

---

src/jumio-kyc/fixtures/image-check.ts
src/jumio-kyc/interfaces/serialized-kyc.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/utils/serialize-kyc.ts
src/redemptions/redemption.module.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts
src/users/users.service.ts

1. Returns better/more discrete error messages for users when calculating eligibility.
2. Returns associated `help_url` if merited
tests pass/test in staging
```
[ ] Yes
```

feat: return informative help messages and urls for KYC

---

src/jumio-api/interfaces/jumio-account-create.ts
src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-api/jumio-api.service.ts
src/jumio-kyc/fixtures/jumio-create-response.ts
src/jumio-kyc/fixtures/watchlist-create-response.ts
src/jumio-kyc/fixtures/workflow-watchlist-pass.ts
src/jumio-kyc/fixtures/workflow-watchlist.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.service.ts
src/redemptions/redemption.service.ts

We had 2 different functions for calculating status of a workflow result, one for standalone, one for normal. However, the models are designed such that each section is just optional if the workflow doesn't specify that. You can easily combine them if you just check if the section is present, then validate that section.
I also saw a lot of fixtures weren't typed, and were being casted to any. Once you type them you realize fields are missing from them, and you don't need to cast them to any in the tests anymore.
This will be used to return the help url from this function.
```
[ ] Yes
```

Combine methods for calculating workflow status

---

src/redemptions/fixtures/approved-repeated-face-failure.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

There are failures resulting from someone attempting KYC > 5 times:
Example below is failing because he is marked as MISMATCHING_DATA_REPEATED_FACE, everything else succeeded. I checked all the linked transactions and they are all for the same account, once he finally used his passport Jumio then recognized all his previous attempts on the same account as a scammer
https://ironfish7143.zendesk.com/agent/tickets/91
https://customer-portal.netverify.com/app/#/transactions/aab161b4-51dc-4dd3-96e3-0eb61fb89464
- removed failure message from repeated face success
- removed check for `LIVENESS_UNDETERMINED` since it is caught by other logic now
tests pass
```
[ ] Yes
```

fix: repeated face same account

---

.github/workflows/deploy-testnet.yml

Upgrading action to use node 16 since node 12 is being deprecated this summer
https://github.com/AkhileshNS/heroku-deploy/releases/tag/v3.12.13
```
[ ] Yes
```

Use actions with NodeJS 16

---

src/common/constants.ts
src/jumio-kyc/kyc.service.spec.ts
src/jumio-kyc/kyc.service.ts

We previously had no fee, this adds a `10 ORE` fee for each airdrop. This will allow us to provide ORE for fee to miners for mining blocks with these transactions.
Tests pass
```
[ ] Yes
```

feat: add airdrop fee for miners so airdrop transactions will picked

---

src/auth/auth.controller.ts

Correctly use subdomains for cookies
N/A
```
[ ] Yes
```

fix(api): Use root domain when setting cookie

---

src/auth/auth.controller.spec.ts
src/auth/auth.controller.ts

When auth pass, redirect user to dashboard
spec
```
[ ] Yes
```
@rohanjadvani @iron-fish/engineering

Redirect to dashboard after auth

---

prisma/migrations/20230405155127_add_sent_ore_redemption/migration.sql
prisma/schema.prisma
src/jumio-kyc/interfaces/serialized-kyc.ts
src/jumio-kyc/utils/serialize-kyc.ts

Adds booking field for sent ore as suggested by @danield9tqh when reviewing airdrop spec.
tests pass
```
[ ] Yes
```

feat: add sent ore to redemption for bookkeeping

---

src/jumio-kyc/interfaces/serialized-kyc.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.service.spec.ts
src/jumio-kyc/utils/serialize-kyc.ts

Adds serialized pool iron payouts for each user to the KYC get response.
NOTE:
I had to add a bunch of mocks for the current time because as the KYC deadline has passed, the tests were failing.
Tests pass
```
[ ] Yes
```

feat: returns pool iron for user on KYC GET request

---

src/jumio-kyc/interfaces/serialized-kyc.ts
src/jumio-kyc/utils/serialize-kyc.ts

Adds transaction hash that will be populated in db once airdrop completed, currently is null for all users.
tests pass
```
[ ] Yes
```

feat: add airdrop_transaction_hash to serialized kyc response

---

prisma/migrations/20230420192411_add_not_null_to_blocks_previous_block_hash/migration.sql
prisma/schema.prisma
src/blocks/dto/upsert-blocks.dto.ts
src/blocks/interfaces/upsert-block-options.ts

This column is always populated
```
[ ] Yes
```

feat(api): Make `blocks.previous_block_hash` not null

---

prisma/migrations/20230421190321_change_average_difficulty_millis_to_average_difficulty_on_blocks_daily/migration.sql
prisma/schema.prisma
src/blocks-daily-loader/blocks-daily-loader.spec.ts
src/blocks-daily/blocks-daily.service.spec.ts
src/blocks-daily/blocks-daily.service.ts
src/blocks-daily/interfaces/create-blocks-daily-options.ts
src/blocks/blocks.controller.spec.ts
src/blocks/blocks.service.spec.ts
src/blocks/blocks.service.ts
src/blocks/interfaces/blocks-date-metrics.ts
src/blocks/utils/blocks-metrics-translator.ts

BigInts in Prisma don't work if they don't fit into 64 bit integers
Manually tested
```
[ ] Yes
```

fix(api): Update average difficulty to decimal type

---

prisma/migrations/20230427184323_add_average_block_size_to_blocks_daily/migration.sql
prisma/schema.prisma
src/blocks-daily-loader/blocks-daily-loader.spec.ts
src/blocks-daily/blocks-daily.service.spec.ts
src/blocks-daily/blocks-daily.service.ts
src/blocks-daily/interfaces/create-blocks-daily-options.ts
src/blocks/blocks.controller.spec.ts
src/blocks/blocks.service.spec.ts
src/blocks/blocks.service.ts
src/blocks/interfaces/blocks-date-metrics.ts
src/blocks/interfaces/serialized-block-metrics.ts
src/blocks/utils/blocks-metrics-translator.ts

Adds `average_block_size` to the `block_metrics` API. This unblocks creating charts for block size in the explorer.
Closes IFL-767
Updated appropriate unit tests
```
[ ] Yes
[X] No
```

feat(api): add average_block_size to the block_metrics API

---

prisma/migrations/20230502165227_add_verified_at_asset/migration.sql
prisma/schema.prisma
src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/interfaces/serialized-asset.ts

Adds verified asset flag to `Asset` model, also returns `verified` data in serialized model.
Plan to run:
```
INSERT INTO assets (name, owner, identifier, metadata, supply, created_transaction_id, verified_at) VALUES ('$IRON', '0000000000000000000000000000000000000000000000000000000000000000', '51f33a2f14f92735e562dc658a5639279ddca3d5079a6d1242b2a588a9cbf44c', 'Iron Fish Native Asset', 0, 56003467, '2023-04-20 09:00:00 PST');
```
Open questions:
1. What should we put for owner?
2. Should we insert a row for `AssetDescriptions`?
```
[ ] Yes
```

feat(ifl-789): verified asset flag

---

src/telemetry/telemetry.controller.ts

Filtering out `block_assembled ` since it isn't needed at the moment
```
[ ] Yes
```

Filter out block_assembled telemetry

---

prisma/migrations/20230526002547_add_expiration_and_serialized_to_transaction/migration.sql
prisma/migrations/20230526195600_add_expiration_sequence_to_transaction/migration.sql
prisma/schema.prisma
src/transactions/dto/upsert-transactions.dto.ts
src/transactions/interfaces/serialized-transaction.ts
src/transactions/interfaces/upsert-transaction-options.ts
src/transactions/transactions.controller.spec.ts
src/transactions/transactions.service.ts
src/transactions/utils/transaction-translator.ts

Adding an optional `expiration` field and `serialized` field to transaction model. We're planning on syncing pending transaction (not on blocks) to the explorer. With this we will want to know if the transaction is expired or not. We may also need the full transaction data at some point in the future either for decryption or other purposes. Since the transaction is not on a block if we don't sync that data and it never makes it into a block then the full data will be forever lost.
Ran unit tests. Planning on testing on testnet api + network before full deploy to mainnet
```
[ ] Yes
```

Add transaction expiration field

---

src/main.ts

`INCENTIVIZED_TESTNET_URL` is not used but it's referenced in `main.js`, which means that by blindly following the instructions in the README, the server won't start.
- `yarn start:dev` and verify that the server starts and works correctly
- `yarn test`
Not a breaking change

Remove the last reference to `INCENTIVIZED_TESTNET_URL`

---

src/assets/assets.controller.spec.ts

This improves the tests for the `/assets` endpoint in the following ways:
* Removes some code duplication. This will be particularly helpful as I'm adding more tests in https://github.com/iron-fish/ironfish-api/pull/1538.
* Improves test isolation by partially cleaning up the database before running each test, so that the assets created by one test case do not affect other test cases.
```
yarn test
```
Not a breaking change.

Improve tests for the `/assets` endpoint

---

src/assets/assets.controller.ts

Responses to the `/assets` endpoint now include the following HTTP header:
Cache-Control: s-maxage=60, stale-if-error=60
which tells shared caches (e.g. Cloudflare) to do the following:
- `s-maxage=60`: serve responses from the cache for a maximum of 60 seconds;
- `stale-if-errors=60`: if the API server is unavailable, serve stale responses from the cache for 60 more seconds before returning errors to clients.
This change should not affect client caches (e.g. web browser caches).
```
$ curl -sv http://localhost:8003/assets
*   Trying 127.0.0.1:8003...
* Connected to localhost (127.0.0.1) port 8003 (#0)
> GET /assets HTTP/1.1
...
< HTTP/1.1 200 OK
...
< Cache-Control: s-maxage=60, stale-if-error=60
...
```
Not a breaking change.

Add `Cache-Control` to `/assets`

---

src/assets/assets.controller.spec.ts
src/assets/assets.service.ts
src/assets/dto/assets-query.dto.ts
src/assets/interfaces/list-assets-optionts.ts

The new boolean `verified` parameter can be used to get only verified assets, or only unverified assets.
Example usage:
```
curl https://api.ironfish.network/assets                 # returns both verified and unverified assets
curl https://api.ironfish.network/assets?verified=true   # only verified assets
curl https://api.ironfish.network/assets?verified=false  # only unverified assets
```
```
$ curl http://localhost:8003/assets | jq
{
"object": "list",
"data": [
{
"object": "asset",
...
"verified_at": null
},
{
"object": "asset",
...
"verified_at": null
},
{
"object": "asset",
...
"verified_at": null
},
{
"object": "asset",
...
"verified_at": "2023-06-16T23:43:14.138Z"
}
],
"metadata": {
"has_next": false,
"has_previous": false
}
}
```
```
$ curl …
```

Add support for the `verified` parameter to the `/assets` endpoint

---

src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/common/utils/request.ts

`/assets` now sets the `Last-Modified` header is all responses. If a request has a valid `If-Modified-Since` header, the endpoint may respond with a 304 (Not Modified) response.
*   Requesting `/assets` without `If-Modified-Since`:
```
$ curl -sv http://localhost:8003/assets
*   Trying 127.0.0.1:8003...
* Connected to localhost (127.0.0.1) port 8003 (#0)
> GET /assets HTTP/1.1
> ...
>
< HTTP/1.1 200 OK
< Last-Modified: Wed, 21 Jun 2023 17:58:10 GMT
< ...
<
{"object":"list","data":[...],"metadata":{"has_next":false,"has_previous":false}}
```
*   Requesting `/assets` with `If-Modified-Since` after the `Last-Modified` time:
```
$ curl -sv -H 'If-Modified-Since: Wed, 21 Jun 2023 17:58:10 GMT' http://localhost:8003/assets
*   Trying 127.0.0.1:8003...
* Connected to localhost (127.0.0.1) port …
```

Add support for `If-Modified-Since` to `/assets`

---

src/assets/assets.controller.ts

This will make Cloudflare cache `/assets` by default, without using any custom page rule.
As stated in the [documentation](https://developers.cloudflare.com/cache/concepts/default-cache-behavior/), Cloudflare requires `max-age` in order to trigger the default cache behavior. The alternative is to enable caching using custom page rules, which I've tried (they work) but that would be harder to maintain.
One advantage of this is that web browsers can now cache responses for 1 minute, which may result in a better user experience. The downside is that propagation delays increase by 1 minute (going from ~1 minute to ~2 minutes).
Local testing:
```
$ curl -sv http://localhost:8003/assets
...
< HTTP/1.1 200 OK
...
< Cache-Control: s-maxage=60, stale-if-error=60
...
```
Once deployed, we should …

Set max-age in Cache-Control directive for `/assets`

---

src/assets/assets.controller.ts

After [changing `Cache-Control` to include `max-age`](https://github.com/iron-fish/ironfish-api/pull/1552), Cloudflare is still returning responses with `cf-cache-status: DYNAMIC`, meaning that caching is not working.
The [Cloudflare documentation](https://developers.cloudflare.com/cache/concepts/default-cache-behavior/) states that both `public` and `max-age` are required in order to enable the default cache behavior.
[`public` should be implied if there is no `Authorization` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), which is why the previous pull request did not include `public`. However, given that the current Cache-Control is not having the desired behavior, it seems that Cloudflare seems to require the explicit presence of `public` in order to …

Set public in Cache-Control directive for `/assets`

---

src/telemetry/telemetry.controller.ts

adds metric useful for monitoring forks, reorgs
see https://github.com/iron-fish/ironfish/pull/3990
```
[ ] Yes
```

whitelists chain_reorg metric in telemetry

---

src/assets/assets.controller.ts

These directives did not have the intended behavior of enabling Cloudflare's cache behavior, hence reverting.
The reason why the directives did not have the intended behavior is that Cloudflare enables the default cache behavior [only for certain file extensions](https://developers.cloudflare.com/cache/concepts/default-cache-behavior/#default-cached-file-extensions). Therefore, we *must* use page rules to enable the cache behavior, there's no other way.
Reverting these directives is not necessary, but `max-age` has an effect on end-user's browsers, and it would increase propagation delays for them.
This reverts commits:
- 412c65e4d8e48bcd331b9ac04856d7a813f9a01a
- 0916f3afa28a92e71dee949c458d6a64323284ed
```
curl -v http://localhost:8003/assets |& grep -i cache-control
```
Not a breaking …

Revert `public` and `max-age` directives for `/assets`

---

README.md
package.json
prisma/seed/main.ts
prisma/seed/tsconfig.eslint.json
prisma/seed/tsconfig.json

This adds a yarn command to help with local testing. For now this only loads test data for assets, but of course it can be extended in the future to load more data.
```
$ yarn db:seed:testing
$ curl http://localhost:8003/assets
```
Not a breaking change.

Add `yarn db:seed:testing` to load some sample data into the database

---

src/versions/versions.service.spec.ts
src/versions/versions.service.ts

The previous version didn't work when comparing v1.9.0 vs v1.10.0
An alternative would be to get all versions and then order them by a custom function. I went with the easier route, but I'm happy to change it. 
1. Sorting version by createdAt date 
2. Updating tests to reflect the above change
```
[ ] Yes
```

sorting latest by created at

---

prisma/migrations/20231224185350_add_transaction_serialized/migration.sql
prisma/schema.prisma
src/transactions/interfaces/serialized-transaction.ts
src/transactions/transactions.controller.spec.ts
src/transactions/utils/transaction-translator.ts

This adds a new field to Transaction called serialized which will contain the full base64 encoded transaction of the Ironfish SDK Transaction type. It also returns it in transactions/find API.
This is the followup PR. https://github.com/iron-fish/ironfish-api/pull/1693
Added test
**No**
Transactions will be sent back with null serialized in the case that it was not sent.

Add serialized transaction field and return in API

---

prisma/migrations/20240111014427_add_transaction_seen_sequence/migration.sql
prisma/schema.prisma
src/blocks-transactions-loader/blocks-transactions-loader.spec.ts
src/blocks-transactions-loader/blocks-transactions-loader.ts
src/transactions/interfaces/upsert-transaction-options.ts
src/transactions/transactions.controller.ts
src/transactions/transactions.rest.module.ts
src/transactions/transactions.service.ts

This will track the current sequence the transaction was first seen at. If we are uploading it in bulk, we use the chain head. If we are seeing it for the first time in the syncer then we use the current block the transaction added it on.
Added tests
```
[ ] Yes
```

Track first transaction seen sequence

---

src/transactions/dto/upsert-transactions.dto.ts
src/transactions/interfaces/upsert-transaction-options.ts
src/transactions/transactions.service.ts

This feeds the serialized field into the DB so it's persisted when the syncer sends it up.
```
[ ] Yes
```

Add serialized TX to the DB

---

src/transactions/interfaces/serialized-transaction.ts
src/transactions/transactions.controller.spec.ts
src/transactions/utils/transaction-translator.ts

This serializes seen_sequence into the transaction response
Added a test
```
[ ] Yes
```

Serialize Transaction.seen_sequence in transaction response

---

prisma/migrations/20240320231350_add_verified_asset_metadata/migration.sql
prisma/schema.prisma
src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/assets.service.ts
src/assets/dto/update-verified-assets-dto.ts

Adding verified asset metadata with multiple fields to assets. Adding endpoint to sync verified assets from a external JSON list of verified assets
Unit tests and testing endpoints locally
```
[ ] Yes
```

Add verified assets metadata

---

.github/workflows/ci.yml
README.md
package.json
src/blocks/blocks.service.ts
yarn.lock

- Changed package.json to use >=20 for NodeJS version so hopefully it will be easier to use 22+ down the line
- Upgraded the Github Actions to use NodeJS 20
- Ran `yarn upgrade hot-shot` to upgrade a sub-dependency that was failing
- Modified a test to cast to a number. I'm not exactly sure why this started failing now, but it is more correct now, technically.
Unit tests locally
Unit tests on github
Deploy to testnet
Only for development if anyone was still using NodeJS 18, so no not really.

Upgrade from NodeJS 18 to 20

---

prisma/migrations/20240401183505_remove_asset_verified_at/migration.sql
prisma/schema.prisma
prisma/seed/main.ts
src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/assets.service.spec.ts
src/assets/assets.service.ts

Moving asset endpoints to use the new verified_metadata field instead of verified_at
Unit tests
```
[ ] Yes
```

Replace verified_at field with verified_asset_metadata

---

src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/interfaces/serialized-asset.ts

To render asset decimals correctly on the block explorer we need the full asset metadata (or at least the decimal).
Unit tests + running API locally
```
[ ] Yes
```

Return full asset metadata from API

---

.env.template
.env.test
package.json
src/app.module.ts
src/test/test-app.ts

I'm not sure the CORS_ENABLED environment variable was working as expected -- it looks like we were expecting it to be a boolean, but without the Joi schema it was remaining as a string, so any non-empty value would resolve to true. I added it to the Joi schema and set the default to true, it should have already been set to true everywhere anyway.
```
[ ] Yes
```

Add CORS_ENABLED to Joi schemas

---

src/main.ts

Allows same origins on both staging and prod, and switches to allowing all Vercel deployments for ironfish for simplicity. Also removes the Allow-Credentials header since we don't really have credentials anymore.
```
[ ] Yes
```

Additional updates to CORS configuration

---

src/bridges/bridges.controller.ts
src/bridges/chainport.service.spec.ts
src/bridges/chainport.service.ts
src/bridges/dto/token-paths-query.dto.ts

* Remove v1 path since we're not using it
* Return token along with networks for token paths
Fixes IFL-3045
Manually curl'd
```
[ ] Yes
```

feat(api): Return token details in token paths

---

src/bridges/chainport.service.ts

I don't know how realistic this typically is, but an asset on preprod has an empty string for the symbol field, which was breaking the token list.
```
[ ] Yes
```

Allow empty string for symbols
