iron-fish/ironfish-api

src/events/events.service.ts
src/events/utils/event-translator.ts

Event record will contains url in metadata field if any
```
[ ] Yes
[x] No
```

IRO-1479: Return url in metadata for event

---

src/app.module.ts
src/influxdb/influxdb.service.spec.ts
src/influxdb/influxdb.service.ts
src/influxdb/interfaces/tag.ts
src/telemetry/__snapshots__/telemetry.controller.spec.ts.snap
src/telemetry/dto/write-telemetry-point.dto.ts
src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts
src/telemetry/telemetry.rest.module.ts
src/test/test-app.ts

Add an endpoint to write data to Influx DB. Also cleaned up some extraneous modules in the test app.
Added unit tests for new module.
```
[ ] Yes
```

feat(api): Add controller to write telemetry data

---

src/influxdb/influxdb.service.spec.ts
src/influxdb/influxdb.service.ts
src/telemetry/__snapshots__/telemetry.controller.spec.ts.snap
src/telemetry/dto/write-telemetry-point.dto.ts
src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts

Allow a client to send multiple data points.
```
[ ] Yes
```

feat(api): Update `/telemetry` to take multiple points

---

src/telemetry/telemetry.controller.spec.ts
src/telemetry/telemetry.controller.ts

Update the minimum version to allow for slower flushes and peer metrics.
Updated unit test.
```
[ ] Yes
[x] No
```

feat(api): Update minimum telemetry version to 0.1.24

---

src/events/__snapshots__/events.controller.spec.ts.snap
src/events/events.controller.spec.ts
src/events/events.controller.ts
src/events/events.service.spec.ts
src/events/events.service.ts
src/faucet-transactions/faucet-transactions.service.spec.ts

Add a delete route for events.
Added unit tests.
```
[ ] Yes
[x] No
```

feat(api): Add `DELETE /events/:id`

---

src/users/users.service.spec.ts
src/users/users.service.ts

Resolves https://github.com/iron-fish/ironfish-api/issues/687
Updated unit test
```
[ ] Yes
[x] No
```

fix(): Remove github filter check on user creation

---

src/events/events.service.spec.ts
src/events/events.service.ts

Stop counting events that occur after 2022 March 12 8 PM UTC.
Updated unit test.
```
[ ] Yes
[x] No
```

feat(api): Add end of phase one check for all events

---

src/events/events.service.spec.ts
src/events/events.service.ts

A user had the wrong number of points for an entry. I deleted the entry and tried to add it again, but it didn't work. This PR is an attempt to fix that. 
```
[ ] Yes
[ ] No
```

Recreate event if deleted

---

.github/workflows/deploy-staging.yml

https://devcenter.heroku.com/changelog-items/2365
Manually testing
```
[ ] Yes
[x] No
```

fix(api): Move away from SSH deploys to Heroku

---

src/telemetry/telemetry.controller.ts

Submit node addresses to telemetry without any association to any other node fields.
Manually verified submission in Influx.
```
[ ] Yes
[x] No
```

feat(api): Add anonymous IP submission to telemetry

---

src/users/dto/user-query.dto.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts

Unit test, manual test
```
[ ] Yes
[x] No
```

Add an endpoint to fetch users by graffiti

---

src/common/constants.ts

Some buffer for phase 1 point processing.
N/A
```
[ ] Yes
[x] No
```

feat(api): Bump COMMUNITY_CONTRIBUTION weekly max to 2000

---

.github/workflows/deploy-phase1-production.yml
.github/workflows/deploy-phase1-staging.yml

Added deploy scripts for phase1, the new secret is here. https://github.com/iron-fish/ironfish-api/settings/secrets/actions and the new pipeline is here https://dashboard.heroku.com/pipelines/f8b344dc-ec6c-4041-8eca-607914fa7df8
Run them once merged
```
[ ] Yes
[x] No
```

Add phase1 deploy scripts

---

.github/workflows/deploy-phase1-staging.yml

Change the branch to deploy from phase1

Change branch for phase1 deploy to phase1

---

src/app.module.ts
src/user-points/user-points.controller.spec.ts
src/user-points/user-points.controller.ts
src/user-points/user-points.rest.module.ts

Add an API endpoint to resync all user points.
Unit tests.
```
[ ] Yes
[x] No
```

feat(api): Add `/user_points/refresh` to resync all points

---

.env.test

Test data was still going into the dev database
Run tests
```
[ ] Yes
[x] No
```

Fix test .env file pointing to dev database

---

src/events/events.service.ts

Just testing this as a style, because it's a little easier for me to
parse the nested tables being created since CTE need to be declared in
dependency order.
Run tests and leaderboard
```
[ ] Yes
[x] No
```

Test CTE pattern for these big queries

---

prisma/migrations/20220413221326_add_node_uptime_to_events_and_user_points/migration.sql
prisma/schema.prisma
src/common/constants.ts
src/events/events.service.spec.ts
src/events/events.service.ts
src/user-points/user-points.jobs.controller.spec.ts

Add NODE_UPTIME event and user_point columns

---

src/telemetry/telemetry.controller.ts
src/telemetry/telemetry.rest.module.ts

Quick fix to avoid tracking uptime prematurely

---

src/blocks/blocks.service.spec.ts
src/events/events.service.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts

I noticed a lot of code has no new lines, or adds lots of new variables
that are hard to trace where they got destructured from. These are just
minor cleanups I think make the code easier to read. It's a bit too
dense for me.
Run tests
```
[ ] Yes
[x] No
```

Minor code formatting and changes

---

src/users/users.service.ts

We changed this in another one, so before refactor I'm changing this one
here
Run test, and test against frontend with production data.
```
[ ] Yes
```

Change leaderboard query to use CTE

---

prisma/migrations/20220419230746_add_send_transaction_event_type/migration.sql
prisma/schema.prisma
src/common/constants.ts
src/events/events.service.spec.ts
src/events/events.service.ts
src/user-points/user-points.jobs.controller.spec.ts

Add SEND_TRANSACTION event type

---

package.json
src/main.ts
webpack.config.js
yarn.lock

Add webpack and a new command to hot reload the API.
Manually ran API and toggled some responses for the health controller.
```
[ ] Yes
```

chore(api): Add hot reloading start command

---

prisma/migrations/20220428175954_remove_deposit_note_index/migration.sql
prisma/migrations/20220428183217_add_unique_contraint_on_deposits/migration.sql
prisma/schema.prisma
src/blocks/blocks.service.ts
src/common/constants.ts
src/events/deposits.controller.spec.ts
src/events/deposits.controller.ts
src/events/deposits.service.ts
src/events/dto/upsert-deposit.dto.ts
src/events/events.module.ts
src/events/events.service.ts
src/events/interfaces/create-event-options.ts

For Phase 2 the Ironfish node will send transaction data that was sent to the the deposit address to the API. The API needs to create events for users if they deposited funds correctly. 
Unit tests
```
[ ] Yes
```

Add Deposit Uploading

---

src/app.module.ts
src/faucet-transactions/__snapshots__/faucet-transactions.controller.spec.ts.snap
src/faucet-transactions/faucet-transactions.controller.spec.ts
src/faucet-transactions/faucet-transactions.controller.ts
src/faucet-transactions/faucet-transactions.rest.module.ts
src/test/test-app.ts

Add flag to disable faucet

---

src/blocks-transactions-loader/blocks-transactions-loader.ts

This shouldn't cause any bugs, but if it was created in the same
transaction it might not be able to be found.
```
[ ] Yes
```

Fix code not using a transaction

---

src/blocks-transactions-loader/blocks-transactions-loader.ts

We were seeing timeouts, and this can take a long time.
- https://github.com/prisma/prisma/blob/fe3d63cc11678d756732ad14887eea62b2590c36/packages/engine-core/src/common/types/Transaction.ts
- https://github.com/prisma/prisma/blob/881366f5c3d18339e1e874a14606913558a0e128/packages/engine-core/src/binary/BinaryEngine.ts#L966
Review with this link for a better life https://github.com/iron-fish/ironfish-api/pull/807/files?diff=split&w=1
```
[ ] Yes
```

Increase block upsert time from 5s to 10s

---

src/blocks-transactions-loader/blocks-transactions-loader.ts

We need to be able to tune the amount of uploaded blocks to avoid this.
```
[ ] Yes
```

Increase timeout for staging

---

src/events/deposits.controller.ts
src/events/deposits.service.ts
src/events/deposits.upsert.service.ts
src/events/events.module.ts

We need this to avoid a circular dependency where events needs to
reference the Deposits service.
Run tests
```
[ ] Yes
```

Move Deposits.upsert into its own service

---

package.json

If you don't clean the DB then the tests will fail
```
[ ] Yes
```

make test:clean the default

---

src/telemetry/telemetry.controller.ts

Turn this on for release
Run tests
```
[ ] Yes
```

Turn on node-uptime

---

src/events/deposits.upsert.service.ts

Review with `?w=1`: https://github.com/iron-fish/ironfish-api/pull/833/files?diff=split&w=1
Quick stop-gap. Eventually want to move this to a graphile job but hopefully this will knock some loose in the mean time
```
[ ] Yes
```

IRO-1873 increase deposits bulk upsert timeout

---

src/events/deposits.upsert.service.ts

fix(api): Pass missing Prisma client when upserting deposits

---

src/users/users.service.spec.ts
src/users/users.service.ts

Use `user_points` to fetch latest event timestamp
Manual testing against staging
```
[ ] Yes
```

feat(api): Speed up `getRank`

---

src/users/users.service.ts

Fixes #870 
When paginating users ordered by rank, the API currently fetches the total rank even if an event type is provided. This change modifies the ranking to check for user points and the latest occurred at timestamp when an event type is defined.
Manually tested against staging
```
[ ] Yes
```

fix(api): Fetch event type rank when paginating for types

---

package.json
yarn.lock

This reverts commit e5ce75fb7fdd6a2aeb0f204859cb0d1e3b1bec40.
```
[ ] Yes
```

Revert "chore(deps): Bump @sindresorhus/is from 4.6.0 to 5.1.0 (#900)"

---

src/health/health.controller.spec.ts
src/health/health.controller.ts

This PR wasn't meant to merge yet, and the lint and test steps weren't
set to required, so it let broken code merge. Opps. Fixed that to
prevent this from happening in the future, and put this up to fix
master.
```
[ ] Yes
```

Fix master

---

prisma/migrations/20220707211805_add_index_to_blocks_transactions/migration.sql
prisma/schema.prisma

Add migration for BlockTransactions.index

---

src/events/deposits.upsert.service.ts

adding dd-trace instrumentation helped to show that the logic of UPSERT_DEPOSIT
jobs does not take long to run. the job has sped up after reducing database
contention from UPDATE_LATEST_POINTS jobs. the dd-tracing implementation is no
longer needed here.
upserts to events did not revive soft-deleted events by setting 'deleted_at' to
null. this created a class of 'mismatched' deposits where points were non-zero
but events were excluded from counts due to the 'deleted_at' field. we have
resolved all of these mismatches except for 177 cases where there is no user
matching the graffiti in the deposit. now that upserts set 'deleted_at' to null
there is no path for new mismatches like this to be created, so we don't need to
include the events table in the queries to identify mismatches.
Is this …

removes dd-trace from deposit upserts, removes events join from mismatch queries

---

src/telemetry/telemetry.controller.ts

It's higher priority and these requests have been failing because of
influx write errors.
Run normal tests
```
[ ] Yes
```

Move influx write after node uptime processing

---

src/events/deposits.upsert.service.ts

does not consider deposits mismatches if their block_sequence is ahead of the
block syncing process. prevents deposits from being marked as mismatches if the
deposits syncer gets ahead of the block syncer (e.g., if the block syncing
process goes down).
makes mismatch queries use the same block sequence criteria.
Closes https://github.com/iron-fish/ironfish/issues/1992
```
[ ] Yes
```

updates mismatched deposits queries for out of sync syncing

---

src/telemetry/telemetry.controller.ts

Adding `block_assembled` metrics to telemetry
```
[ ] Yes
```

add block_assembled metric to telemetry

---

src/events/deposits.upsert.service.spec.ts
src/events/events.service.ts

Scales the amount of points based on deposit size. This is related to the PRs:
https://github.com/iron-fish/ironfish/pull/2391
https://github.com/iron-fish/ironfish-api/pull/1053
Unittests

feat: add logic to adjust deposit points for increased deposit size

---

package.json
prisma/schema.prisma

chore: format prisma schema

---

src/events/events.service.ts

Use Ore to calculate point, instead of IRON

---

src/health/health.controller.spec.ts
src/health/health.controller.ts

So we can disable this separately and run it when ever we want.
```
[ ] Yes
```

Split out deposit health from admin health

---

src/events/deposits.upsert.service.spec.ts
src/events/events.service.ts

We should add tests in these types of cases lest we make the same mistake again.
Run tests
```
[ ] Yes
```

Add test for deposit points calculation

---

src/telemetry/telemetry.controller.ts

whitelists fee_rate_estimate metric in telemetry

---

src/graphile-worker/graphile-worker.microservice.ts

Add log for graphile worker

---

src/graphile-worker/graphile-worker.microservice.ts

Measure and report worker idle time

---

src/events/events.service.ts
src/user-points/interfaces/upsert-user-points-options.ts

This turns 3 queries into 1
```
[ ] Yes
```

Optimize updateLatestPoints

---

src/events/deposits.controller.spec.ts
src/events/deposits.upsert.service.spec.ts
src/events/deposits.upsert.service.ts

Checks that a deposit operation is being applied cleanly, or fails. It requires fixing almost every test. You should review with https://github.com/iron-fish/ironfish-api/pull/1103/files?diff=split&w=1
```
[ ] Yes
```

Add check that deposit connection is correct

---

src/events/deposits.upsert.service.spec.ts
src/events/deposits.upsert.service.ts

We require in order execution here, you cannot defer this.
```
[ ] Yes
```

Execute upsert deposits in the request thread

---

docker-compose.yml
src/events/masp.upsert.service.spec.ts
src/users/interfaces/serialized-user-metrics.ts
src/users/users.controller.ts

Realized we needed this change when I was trying to change the user profile page.
```
[ ] Yes
```

chore: update user metrics dto

---

src/users/users.controller.ts

Missed this required update for frontend user profile
```
[ ] Yes
```

chore: update pool info return

---

src/common/constants.ts
src/events/deposits.upsert.service.spec.ts
src/events/events.service.spec.ts
src/events/events.service.ts

We need this since we're back crediting points.
```
[ ] Yes
```

Change points to force 0.1 allocation before block height

---

src/events/masp.controller.spec.ts
src/events/masp.upsert.service.spec.ts
src/events/masp.upsert.service.ts

chore: add assert to check empty transactions

---

src/events/masp.upsert.service.ts

Not super excited about this change, since it can potentially introduce a bug in the future if the conditionals are updated, but does save a query when doing connected blocks.
```
[ ] Yes
```

chore: move users query to inside disconnected conditional

---

src/common/constants.ts
src/events/deposits.upsert.service.ts

This will disable deposits past 288,888 no longer providing credit.
```
[ ] Yes
```

Disable deposits past block 288,888

---

.github/workflows/deploy-phase1-production.yml
.github/workflows/deploy-phase2-production.yml
.github/workflows/deploy-phase2-staging.yml
.github/workflows/deploy-staging.yml

This adds the deploy scripts for the phase2 branch.
```
[ ] Yes
```

Add phase2 deploy scripts

---

src/users/users.service.spec.ts
src/users/users.service.ts

Update constants that are returned and add test.
unittest
```
[ ] Yes
```

fix: bug in MASP leaderboard

---

src/common/constants.ts

Update multi asset points

---

src/events/events.service.spec.ts
src/events/events.service.ts

Immediately enqueue jobs to resync points for a user
N/A
```
[ ] Yes
```

feat(api): Remove throttling when updating points

---

src/events/multi-asset.upsert.service.ts

Fix transaction already closed error
N/A
```
[ ] Yes
```

feat(api): Bump transaction timeout for multi asset upserts

---

.github/workflows/ci.yml
package.json

Upgrade to LTS
CI
```
[ ] Yes
```

chore(api): Bump Node to v18

---

prisma/migrations/20230201202835_add_hashed_ip_address_to_users/migration.sql
prisma/schema.prisma

Add column to track hashed IP addresses for testnet
N/A
```
[ ] Yes
```

feat(api): Add hashed ip address column to `users`

---

src/telemetry/telemetry.controller.ts

Upload version tags when writing IP addresses
Manual testing
```
[ ] Yes
```

feat(api): Add version tag to IP

---

src/users/dto/create-user.dto.ts

We aren't gonna verify this yet, but front end is gonna start collecting scores.
```
[ ] Yes
```

Add optional v3 captcha token we will start sending up

---

prisma/migrations/20230203223817_create_assets_and_asset_descriptions/migration.sql
prisma/schema.prisma

Create `assets` and `asset_descriptions` to persist assets from the chain
Manually run migrations
```
[ ] Yes
```

feat(api): Create asset tables

---

src/transactions/dto/burn.dto.ts
src/transactions/dto/mint.dto.ts
src/transactions/dto/upsert-transactions.dto.ts

Add DTOs for transaction mints and burns
N/A
```
[ ] Yes
```

feat(api): Add DTOs for mint and burn

---

src/recaptcha-verification/recaptcha-verification.service.spec.ts
src/recaptcha-verification/recaptcha-verification.service.ts
src/users/users.controller.ts

This wasn't actually verifying the score.
```
[ ] Yes
```

Do verification of recaptcha token

---

prisma/migrations/20230209203545_add_unique_identifier_constraint_to_assets/migration.sql
prisma/schema.prisma

Ensure identifiers are unique
Existing tests
```
[ ] Yes
```

feat(api): Add unique constraint on identifiers for assets

---

src/assets/assets.module.ts
src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/assets/interfaces/create-asset-options.ts
src/test/test-app.ts

Create service to interact with assets table. Enables upserts, reads, and supply adjusting
Unit tests
```
[ ] Yes
```

feat(api): Create assets module

---

src/asset-descriptions/asset-descriptions.module.ts
src/asset-descriptions/asset-descriptions.service.spec.ts
src/asset-descriptions/asset-descriptions.service.ts
src/assets-loader/assets-loader.module.ts
src/assets-loader/assets-loader.spec.ts
src/assets-loader/assets-loader.ts
src/assets/assets.module.ts
src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/assets/interfaces/create-asset-options.ts
src/blocks-transactions-loader/blocks-transactions-loader.module.ts
src/blocks-transactions-loader/blocks-transactions-loader.spec.ts
src/blocks-transactions-loader/blocks-transactions-loader.ts
src/transactions/dto/upsert-transactions.dto.ts
src/transactions/transactions.service.ts

Add module which will upsert assets and create/delete descriptions
Unit tests
```
[ ] Yes
```

feat(api): Add asset loader

---

src/assets-loader/assets-loader.ts

fix(api): Fix hash standardization

---

src/app.module.ts
src/assets-loader/assets-loader.ts
src/assets/__snapshots__/assets.controller.spec.ts.snap
src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/assets.module.ts
src/assets/assets.rest.module.ts
src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/assets/dto/asset-query-dto.ts
src/assets/interfaces/serialized-asset.ts
src/transactions/transactions.service.ts

Add endpoint to fetch asset by identifier
Unit tests
```
[ ] Yes
```

feat(api): Add `/assets/find`

---

src/app.module.ts
src/asset-descriptions/__snapshots__/asset-descriptions.controller.spec.ts.snap
src/asset-descriptions/asset-descriptions.controller.spec.ts
src/asset-descriptions/asset-descriptions.controller.ts
src/asset-descriptions/asset-descriptions.module.ts
src/asset-descriptions/asset-descriptions.rest.module.ts
src/asset-descriptions/asset-descriptions.service.spec.ts
src/asset-descriptions/asset-descriptions.service.ts
src/asset-descriptions/dto/asset-descriptions-query.dto.ts
src/asset-descriptions/interfaces/list-asset-descriptions-options.ts
src/asset-descriptions/interfaces/serialized-asset-description.ts

Add route to list asset descriptions
Unit tests
```
[ ] Yes
```

feat(api): Add asset descriptions controller

---

src/blocks-transactions-loader/blocks-transactions-loader.ts

Speed up asset processing by removing the queue
N/A
```
[ ] Yes
```

feat(api): Remove asset queue

---

src/assets-loader/assets-loader.ts

Use same check as in node. We are skipping descriptions since the post check in the node was added after some large mints already occurred. 
N/A
```
[ ] Yes
```

feat(api): Check max mint and burn value

---

src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/assets/interfaces/list-assets-optionts.ts

Fetch paginated assets
Unit tests
```
[ ] Yes
```

feat(api): Add list service method for assets

---

src/asset-descriptions/asset-descriptions.controller.ts
src/asset-descriptions/asset-descriptions.service.spec.ts
src/asset-descriptions/asset-descriptions.service.ts
src/asset-descriptions/utils/asset-descriptions.translator.ts
src/assets-loader/assets-loader.ts
src/blocks/blocks.controller.ts
src/blocks/blocks.rest.module.ts
src/blocks/utils/block-translator.ts
src/transactions/interfaces/serialized-transaction.ts
src/transactions/transactions.controller.ts
src/transactions/transactions.rest.module.ts
src/transactions/utils/transaction-translator.ts

Return transaction mints and burns where possible
Existing tests
```
[ ] Yes
```

feat(api): Return mints and burns with transactions

---

src/asset-descriptions/asset-descriptions.controller.spec.ts
src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/assets.rest.module.ts
src/assets/interfaces/serialized-asset.ts

Return created block timestamp for assets
Unit tests
```
[ ] Yes
```

feat(api): Return created timestamp for asset

---

src/user-rank/user-ranks.loader.service.ts

These refreshes are taking a bit close to 1m
```
[ ] Yes
```

feat(api): Change frequency of materialized view from 1m to 5m

---

src/asset-descriptions/asset-descriptions.controller.ts
src/asset-descriptions/interfaces/serialized-asset-description.ts
src/asset-descriptions/utils/asset-descriptions.translator.ts
src/assets-loader/assets-loader.ts
src/assets/assets.service.ts
src/blocks/blocks.controller.ts
src/blocks/blocks.rest.module.ts
src/transactions/transactions.controller.ts
src/transactions/transactions.rest.module.ts
src/transactions/utils/transaction-translator.ts

Return asset info along with descriptions
Manual testing
```
[ ] Yes
```

feat(api): Return asset identifier and name with descriptions

---

src/users/users.controller.spec.ts
src/users/utils/user-translator.ts

Remove node uptime threshold

---

src/users/dto/update-user.dto.ts
src/users/interfaces/update-user-options.ts
src/users/users.controller.ts
src/users/users.service.spec.ts
src/users/users.service.ts

Don't allow for country updates
Existing tests
```
[ ] Yes
```

feat(api): Disable country updates

---

.envrc
.gitignore
flake.lock
flake.nix

chore(api): Add flake.nix

---

src/users/dto/update-user.dto.ts
src/users/interfaces/update-user-options.ts
src/users/users-updater.module.ts
src/users/users-updater.spec.ts
src/users/users-updater.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts
src/users/users.service.spec.ts
src/users/users.service.ts

Disable graffiti updates
Removed unit tests
```
[ ] Yes
```

feat(api): Remove graffiti updates

---

prisma/migrations/20230301220103_add_ineligible_reason_to_users/migration.sql
prisma/schema.prisma

Add a nullable text field for ineligible reason 
```
[ ] Yes
```

feat: add inegligible_reason field to user model

---

src/jumio-kyc/interfaces/serialized-kyc-config.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts

Add config on testnet pools and kyc / airdrop dates
Unit test
```
[ ] Yes
```

feat(api): Add `GET /kyc/config`

---

prisma/migrations/20230301233838_add_id_info_to_redemption/migration.sql
prisma/schema.prisma
src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.service.ts
src/redemptions/redemption.service.ts

Add ban list for countries, we can add response from jumio 
Tests pass
```
[ ] Yes
```

feat: add ban list to checks for attempt

---

prisma/migrations/20230302001406_add_pool123_points_to_user_points/migration.sql
prisma/schema.prisma

Add columns to cache data across phases
N/A
```
[ ] Yes
```

feat(api): Add pool 1/2/3 points to `user_points`

---

src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/kyc.service.ts
src/redemptions/redemption.service.ts

Change check to use pool points

---

src/jumio-kyc/interfaces/serialized-kyc.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/utils/serialize-kyc.ts

Add can_attempt to get redemption

---

prisma/migrations/20230303012713_add_user_enable_kyc/migration.sql
prisma/schema.prisma
src/jumio-kyc/kyc.controller.spec.ts
src/redemptions/redemption.service.ts
src/users/interfaces/create-user-options.ts
src/users/interfaces/serialized-user.ts
src/users/users.service.ts
src/users/utils/user-translator.ts

This is for gating KYC on users
```
[ ] Yes
```

Add user.enable_kyc

---

src/jumio-kyc/interfaces/serialized-kyc.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/kyc.service.ts
src/jumio-kyc/utils/serialize-kyc.ts
src/redemptions/redemption.service.ts

WIP: refactor attempts code

---

prisma/migrations/20230303223949_add_redemption_last_callback/migration.sql
prisma/schema.prisma
src/jumio-kyc/kyc.service.ts
src/jumio-transactions/jumio-transaction.service.ts

This is useful for debugging
- rename `JumioTransaction.latest_callback_at` -> `JumioTransaction.last_callback_at`
- Add `JumioTransaction.latest_callback`
```
[ ] Yes
```

Store callback JSON in the DB

---

prisma/migrations/20230303225555_add_redemption_max_attempts/migration.sql
prisma/schema.prisma
src/redemptions/redemption.service.ts

This will let us override max attempts for certain users to increase it.
```
[ ] Yes
```

Add Redemption.kyc_max_attempts

---

src/jumio-api/jumio-api.module.ts
src/jumio-api/jumio-api.service.ts

Add server logs for failing jumio requests

---

src/jumio-api/jumio-api.service.spec.ts
src/jumio-api/jumio-api.service.ts

Use put for account update

---

src/jumio-api/jumio-api.service.ts

It doesn't look like this route is mapped in the API
N/A
```
[ ] Yes
```

fix(api): Fix path for jumio callback

---

src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts

Always send back eligibility in can_attempt

---

src/app.module.ts
src/jumio-kyc/kyc.jobs.controller.ts
src/jumio-kyc/kyc.jobs.module.ts
src/jumio-kyc/kyc.service.spec.ts

Adds module for kyc jobs
tests pass
```
[ ] Yes
```

fix: add kyc jobs module

---

src/jumio-kyc/interfaces/serialized-kyc.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/utils/serialize-kyc.ts

Add new can_post field to returning KYC

---

prisma/migrations/20230304225854_add_waiting_kyc_status/migration.sql
prisma/schema.prisma
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/kyc.service.spec.ts
src/jumio-kyc/kyc.service.ts

Add complete endpoint

---

src/jumio-kyc/kyc.service.ts

Multiple callbacks could incorrectly transition the redemption because of redelivery.
https://github.com/iron-fish/ironfish-api/pull/1305/files?diff=split&w=1
```
[ ] Yes
```

Add locks to changing redemption state

---

src/jumio-kyc/interfaces/serialized-kyc.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/kyc.rest.module.ts
src/jumio-kyc/utils/serialize-kyc.ts

Send back kyc_max_attempts in serializedKYC

---

src/jumio-api/interfaces/jumio-account-create.ts
src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-api/jumio-api.service.ts

So we don't store extracted data
```
[ ] Yes
```

Don't store extraction data

---

src/jumio-api/jumio-api.service.spec.ts
src/jumio-api/jumio-api.service.ts

Turns on watch list in workflow
```
[ ] Yes
```

Turn on watch list for capabilities

---

src/jumio-kyc/kyc.controller.ts
src/redemptions/redemption.service.ts

This will allow us to display a better message when you hit your max tries.
```
[ ] Yes
```

Fail can_attempt because of max tries

---

src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts

These dates are swapped
Unit test
```
[ ] Yes
```

fix(api): Switch airdrop / kyc dates

---

.github/workflows/ci.yml
package.json
prisma/schema.prisma
src/events/events.service.spec.ts
src/events/events.service.ts
yarn.lock

Seeing db timeouts in logs
N/A
```
[ ] Yes
```

fix(api): Remove tx for lifetime query

---

src/redemptions/redemption.service.ts

Checks if there is an ineligibility reason set on the user from @mat-if work.
tests pass
```
[ ] Yes
```

fix: ineligible reason check in eligiblity calculation

---

src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.service.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

Updates strings so we can display to user why they can't currently access KYC
Tests pass
```
[ ] Yes
```

chore: update returned reason strings for user display

---

src/redemptions/redemption.service.ts

minor clarification + typo fix to redemption message

---

src/redemptions/redemption.service.ts

Changes from negative to positive messaging.
Tests pass
```
[ ] Yes
```

feat: add allocations table (#1325)

---

src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

Only exclude eligiblity from attempts if not successful

---

src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/redemptions/redemption.service.ts

Updates public address of user via PUT to `/kyc`
tests pass
```
[ ] Yes
```

feat: allows user to update public address via PUT to /kyc

---

src/common/constants.ts
src/jumio-kyc/kyc.controller.spec.ts

Deadlines for 
KYC: Apr 14th
Airdrop: Apr 21th
tests pass
```
[ ] Yes
```

chore: update deadlines to all be the same for all phases

---

.github/workflows/deploy-phase3-production.yml
.github/workflows/deploy-phase3-staging.yml

Adding deploy jobs for Phase 3 archival website
```
[ ] Yes
```

Add phase 3 deploy jobs

---

src/auth/guards/magic-link.guard.ts
src/auth/strategies/magic-link.strategy.ts
src/users/__snapshots__/me.controller.spec.ts.snap
src/users/__snapshots__/users.controller.spec.ts.snap
src/users/me.controller.spec.ts

Throw detailed error message during authentication.
spec test
```
[ ] Yes
```

Add error handling in Auth

---

src/redemptions/redemption.service.ts

They are now easier to see all at once, and update.
```
[ ] Yes
```

Factored out all of the help urls

---

src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

This could be used to expose pictures of people to see if they own accounts and how much money they'll get.
```
[ ] Yes
```

Dont list other duplicate graffitis

---

src/redemptions/redemption.service.ts

Made some flow changes to getEligibility

---

src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/kyc.service.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

This surfaces the calculateStatus reason for the last jumio transaction.
```
[ ] Yes
```

Surface failureReason and failureUrl

---

src/jumio-api/interfaces/jumio-transaction-retrieve.ts
src/jumio-kyc/fixtures/callback-expired.ts
src/jumio-kyc/fixtures/callback.ts
src/jumio-kyc/fixtures/workflow-expired.ts
src/jumio-kyc/interfaces/jumio-callback-data.ts
src/jumio-kyc/kyc.controller.spec.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/kyc.service.spec.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

It looks like something was failing her, so I added a test for the expired use case. I did find some bugs, but also I found that the types weren't correct. I made many cases handle optionality, which things are optional in the case that a workflow doesn't execute or is expired.
Added many tests
```
[ ] Yes
```

Add tests for expired callbacks, workflows, and help_url

---

src/auth/guards/magic-link.guard.ts
src/auth/strategies/magic-link.strategy.ts
src/users/__snapshots__/me.controller.spec.ts.snap
src/users/__snapshots__/users.controller.spec.ts.snap
src/users/me.controller.spec.ts

Refactor magic link guard
spec
```
[ ] Yes
```
@rohanjadvani

Refactor magic link guard

---

src/jumio-kyc/fixtures/workflow-unsupported.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

These are being caught as "unknown".
```
[ ] Yes
```

Properly detect unsupported document

---

src/common/constants.ts
src/jumio-kyc/kyc.controller.ts
src/jumio-kyc/kyc.service.ts

You can use this to estimate someones reward using `GET /kyc/estimate/1080`
```
[ ] Yes
```

Add API to estimate reward

---

src/redemptions/fixtures/approved-liveness-undertermined.ts
src/redemptions/redemption.service.spec.ts
src/redemptions/redemption.service.ts

This failure was seen in this workflow:
https://customer-portal.netverify.com/app/#/transactions/aa9898b0-023c-479e-8b48-79f3bbc333a3
From this ticket:
https://ironfish7143.zendesk.com/agent/tickets/647
It should be a pass
tests pass
```
[ ] Yes
```

fix: approve the liveness undetermined failure

---

src/api-config/api-config.service.ts
src/auth/__snapshots__/auth.controller.spec.ts.snap
src/auth/auth.controller.spec.ts
src/auth/auth.controller.ts
src/auth/dto/login-query.dto.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts

Add a login route which takes a JWT
Unit tests
```
[ ] Yes
```

feat(api): Add JWT login route

---

src/auth/auth.controller.spec.ts
src/auth/auth.controller.ts

Add route to clear JWT cookie
Unit test
```
[ ] Yes
```

feat(api): Add `/logout`

---

src/auth/strategies/magic-link.strategy.ts
src/users/__snapshots__/me.controller.spec.ts.snap
src/users/me.controller.spec.ts
src/users/users.controller.ts

Use second instead of ms
spec 
```
[ ] Yes
```
@rohanjadvani

Use second instead of ms for iat in. jwt payload

---

src/blocks-daily/blocks-daily.service.ts

Update the default chart date to mainnet start
N/A
```
[ ] Yes
```

fix(api): Update daily default start date

---

src/blocks/blocks.controller.spec.ts
src/blocks/blocks.controller.ts
src/blocks/interfaces/serialized-block-head.ts
src/common/utils/bigint.ts

Return network hash rate as of latest block
Unit test
```
[ ] Yes
```

feat(api): Return hash rate in `/blocks/head`

---

src/blocks-daily-loader/blocks-daily-loader.spec.ts
src/blocks-daily/blocks-daily.service.spec.ts
src/blocks-daily/interfaces/create-blocks-daily-options.ts
src/blocks/blocks.controller.spec.ts
src/blocks/blocks.service.spec.ts
src/blocks/blocks.service.ts
src/blocks/interfaces/blocks-date-metrics.ts

The ORM is crashing when aggregating these records
Unit tests
```
[ ] Yes
```

fix(api): Fix bigint write to prisma for daily charts

---

src/blocks-daily/blocks-daily.jobs.controller.spec.ts
src/blocks/blocks.controller.spec.ts
src/blocks/blocks.controller.ts
src/blocks/blocks.service.ts
src/blocks/interfaces/serialized-block-head.ts

Return latest block reward in API response
Unit test
```
[ ] Yes
```

feat(api): Return block reward

---

src/blocks/blocks.controller.spec.ts
src/blocks/blocks.controller.ts
src/blocks/blocks.service.spec.ts
src/blocks/blocks.service.ts
src/blocks/interfaces/serialized-block-head.ts
src/common/constants.ts

Return available supplies in latest block head endpoint
Unit tests
```
[ ] Yes
```

feat(api): Return total and circulating supply in head

---

src/blocks/blocks.controller.ts

Circulating supply is incorrect
Manually tested
```
[ ] Yes
```

fix(api): Fix percentages and divide by 100 for supplies

---

prisma/migrations/20230509191724_drop_testnet_tables/migration.sql
prisma/schema.prisma

Drop any tables related to incentivized testnet. Backup is present under Phase 3 in Heroku.
N/A
```
[ ] Yes
```

feat(api): Drop testnet tables

---

src/telemetry/telemetry.controller.ts

This will allow us to check `node_addresses` for type. Other metrics should automatically have the tag `agent` once this PR ships to mainnet.
https://github.com/iron-fish/ironfish/pull/3914/files
```
[ ] Yes
```

feat(ifl-934): agent tag for differentiating telemetry requests

---

src/transactions/utils/transaction-translator.ts

Make serialization of transaction consistent whether it's with blocks or not
Unit tests
```
[ ] Yes
```

Consistent transaction serialization

---

src/app.module.ts
src/supply/supply.controller.spec.ts
src/supply/supply.controller.ts
src/supply/supply.rest.module.ts

Adds separate endpoints for fetching circulating and total supplies
Unit tests
```
[ ] Yes
```

feat(api): Add supply controller

---

prisma/migrations/20240322000015_rename_verified_asset_metadata/migration.sql
prisma/schema.prisma

Forgot to add a mapping for snake case naming of the table. No items yet exist in the table so this should not affect existing data
Unit tests
```
[ ] Yes
```

Rename verified asset metadata table

---

.github/workflows/deploy-testnet.yml

chore(api): Update github ci action version for heroku

---

.github/workflows/deploy-testnet.yml

fix(api): Fix the version for akhileshns/heroku-deploy

---

src/main.ts

feat(api): Add flag to enable cors

---

src/blocks-transactions/blocks-transactions.service.ts
src/transactions/transactions.service.ts

feat(api): Use read client for transactions data

---

src/bridges/chainport.service.ts

feat(api): Update events to incrementing metrics for chainport

---

src/bridges/chainport.service.ts

Passes through Chainport error messages as UnprocessableEntity instead of throwing an empty BadGateway. Cloudflare kind of eats 502s and replaces them with their own page, so I'm not sure that's what we want for validation errors on their side.
```
[ ] Yes
```

Pass through Chainport errors
